import Fuse from "fuse.js";
import { useCallback, useEffect, useMemo, useState } from "react";

export interface SearchResult {
  id: string;
  title: string;
  description: string;
  route: string;
  category: "pages" | "elements" | "tools" | "glossary";
  icon?: string;
  metadata?: string;
}

const pageData: SearchResult[] = [
  {
    id: "p1",
    title: "Home",
    description: "NuclearEdu landing page",
    route: "/",
    category: "pages",
    icon: "BookOpen",
  },
  {
    id: "p2",
    title: "Atomic Models",
    description: "Historical timeline of atomic models",
    route: "/atoms/atomic-models",
    category: "pages",
    icon: "BookOpen",
  },
  {
    id: "p3",
    title: "Subatomic Particles",
    description: "Quarks, leptons, bosons and the Standard Model",
    route: "/atoms/subatomic-particles",
    category: "pages",
    icon: "BookOpen",
  },
  {
    id: "p4",
    title: "Quantum Mechanics",
    description: "Wavefunctions, uncertainty principle, quantum numbers",
    route: "/atoms/quantum-mechanics",
    category: "pages",
    icon: "BookOpen",
  },
  {
    id: "p5",
    title: "Orbitals",
    description: "Electron orbital shapes and probability clouds",
    route: "/atoms/orbitals",
    category: "pages",
    icon: "BookOpen",
  },
  {
    id: "p6",
    title: "Electron Configuration",
    description: "Aufbau principle, Hund's rule, orbital filling",
    route: "/atoms/electron-config",
    category: "pages",
    icon: "BookOpen",
  },
  {
    id: "p7",
    title: "Spectral Series",
    description: "Hydrogen spectral lines and Rydberg formula",
    route: "/atoms/spectral-series",
    category: "pages",
    icon: "BookOpen",
  },
  {
    id: "p8",
    title: "Nuclear Basics",
    description: "Introduction to nuclear science",
    route: "/basics/atom-structure",
    category: "pages",
    icon: "BookOpen",
  },
  {
    id: "p9",
    title: "Nuclear Reactions",
    description: "Fission, fusion, and decay processes",
    route: "/reactions/decay",
    category: "pages",
    icon: "BookOpen",
  },
  {
    id: "p10",
    title: "Reactors",
    description: "PWR, BWR, CANDU, SMR reactor types",
    route: "/reactors/pwr",
    category: "pages",
    icon: "BookOpen",
  },
  {
    id: "p11",
    title: "Radiation Types",
    description: "Alpha, beta, gamma, neutron radiation",
    route: "/radiation/types",
    category: "pages",
    icon: "BookOpen",
  },
  {
    id: "p12",
    title: "Glossary",
    description: "200+ nuclear science terms",
    route: "/glossary",
    category: "pages",
    icon: "BookOpen",
  },
  {
    id: "p13",
    title: "About",
    description: "About NuclearEdu platform",
    route: "/about",
    category: "pages",
    icon: "BookOpen",
  },
  {
    id: "p14",
    title: "Nucleus Visualizer",
    description: "Interactive 3D nucleus visualization",
    route: "/visualizations/nucleus",
    category: "pages",
    icon: "BookOpen",
  },
  {
    id: "p15",
    title: "Decay Chain Explorer",
    description: "Animated decay chain simulator",
    route: "/visualizations/decay-chain",
    category: "pages",
    icon: "BookOpen",
  },
  {
    id: "p16",
    title: "Chart of Nuclides",
    description: "Interactive nuclide chart with isotope data",
    route: "/visualizations/nuclide-chart",
    category: "pages",
    icon: "BookOpen",
  },
  {
    id: "p17",
    title: "Reactor Cross-Section",
    description: "Reactor core visualization and simulation",
    route: "/visualizations/reactor",
    category: "pages",
    icon: "BookOpen",
  },
  {
    id: "p18",
    title: "Reactor World Map",
    description: "Global nuclear power plant locations",
    route: "/visualizations/reactor-world-map",
    category: "pages",
    icon: "BookOpen",
  },
  {
    id: "p19",
    title: "Periodic Table",
    description: "Interactive periodic table with nuclear data",
    route: "/visualizations/periodic-table",
    category: "pages",
    icon: "BookOpen",
  },
  {
    id: "p20",
    title: "Valley of Stability",
    description: "3D nuclear stability landscape",
    route: "/visualizations/valley-of-stability",
    category: "pages",
    icon: "BookOpen",
  },
  {
    id: "p21",
    title: "Quantum Visualizer",
    description: "Quantum mechanical wavefunction visualizations",
    route: "/visualizations/quantum",
    category: "pages",
    icon: "BookOpen",
  },
  {
    id: "p22",
    title: "Feynman Diagrams",
    description: "Interactive Feynman diagram generator",
    route: "/visualizations/feynman-diagrams",
    category: "pages",
    icon: "BookOpen",
  },
  {
    id: "p23",
    title: "Safety Principles",
    description: "Nuclear safety fundamentals",
    route: "/safety/principles",
    category: "pages",
    icon: "BookOpen",
  },
  {
    id: "p24",
    title: "Regulation",
    description: "NRC, IAEA, and international regulations",
    route: "/safety/regulation",
    category: "pages",
    icon: "BookOpen",
  },
  {
    id: "p25",
    title: "Accident Analysis",
    description: "Chernobyl, Fukushima, TMI case studies",
    route: "/safety/accidents",
    category: "pages",
    icon: "BookOpen",
  },
  {
    id: "p26",
    title: "Waste Management",
    description: "Nuclear waste disposal and storage",
    route: "/safety/waste-management",
    category: "pages",
    icon: "BookOpen",
  },
  {
    id: "p27",
    title: "Radiation Safety",
    description: "ALARA, shielding, dosimetry",
    route: "/safety/radiation",
    category: "pages",
    icon: "BookOpen",
  },
  {
    id: "p28",
    title: "Learning Lab",
    description: "Quizzes, progress tracking, and badges",
    route: "/learning-lab",
    category: "pages",
    icon: "BookOpen",
  },
  {
    id: "p29",
    title: "News & Research",
    description: "Latest nuclear science news",
    route: "/news",
    category: "pages",
    icon: "BookOpen",
  },
  {
    id: "p30",
    title: "Nuclear Medicine",
    description: "Medical isotopes and applications",
    route: "/applications/medicine",
    category: "pages",
    icon: "BookOpen",
  },
  {
    id: "p31",
    title: "Fusion Energy",
    description: "ITER, NIF, and stellarator progress",
    route: "/applications/fusion",
    category: "pages",
    icon: "BookOpen",
  },
  {
    id: "p32",
    title: "Small Modular Reactors",
    description: "SMR designs and deployment",
    route: "/applications/smrs",
    category: "pages",
    icon: "BookOpen",
  },
  {
    id: "p33",
    title: "Nuclear History",
    description: "Timeline from 1896 to present",
    route: "/history",
    category: "pages",
    icon: "BookOpen",
  },
  {
    id: "p34",
    title: "Weapons History",
    description: "Manhattan Project and Cold War",
    route: "/history/weapons",
    category: "pages",
    icon: "BookOpen",
  },
  {
    id: "p35",
    title: "Progress Dashboard",
    description: "Learning progress and achievements",
    route: "/dashboard",
    category: "pages",
    icon: "BookOpen",
  },
  {
    id: "p36",
    title: "Isotope Comparison",
    description: "Side-by-side isotope property comparison",
    route: "/tools/isotope-comparison",
    category: "pages",
    icon: "BookOpen",
  },
  {
    id: "p37",
    title: "Radioisotope Database",
    description: "Database of radioactive isotopes",
    route: "/tools/radioisotope-database",
    category: "pages",
    icon: "BookOpen",
  },
  {
    id: "p38",
    title: "Cross-Section Viewer",
    description: "Neutron cross-section data plots",
    route: "/tools/cross-section-viewer",
    category: "pages",
    icon: "BookOpen",
  },
  {
    id: "p39",
    title: "Dosimetry Calculator",
    description: "Radiation dose calculations",
    route: "/tools/dosimetry-calculator",
    category: "pages",
    icon: "BookOpen",
  },
  {
    id: "p40",
    title: "Carbon Dating Calculator",
    description: "Radiocarbon dating age calculator",
    route: "/tools/carbon-dating",
    category: "pages",
    icon: "BookOpen",
  },
  {
    id: "p41",
    title: "Criticality Calculator",
    description: "k-effective and critical mass estimator",
    route: "/tools/criticality-calculator",
    category: "pages",
    icon: "BookOpen",
  },
  {
    id: "p42",
    title: "Dose Rate Calculator",
    description: "Inverse-square law dose calculator",
    route: "/tools/dose-rate-calculator",
    category: "pages",
    icon: "BookOpen",
  },
  {
    id: "p43",
    title: "Fuel Cycle Visualizer",
    description: "Nuclear fuel cycle animation",
    route: "/tools/fuel-cycle",
    category: "pages",
    icon: "BookOpen",
  },
  {
    id: "p44",
    title: "Monte Carlo Simulation",
    description: "Stochastic neutron transport simulation",
    route: "/tools/monte-carlo-sim",
    category: "pages",
    icon: "BookOpen",
  },
  {
    id: "p45",
    title: "Relativistic Kinematics",
    description: "E=mc² and Lorentz transformations",
    route: "/tools/relativistic-kinematics",
    category: "pages",
    icon: "BookOpen",
  },
  {
    id: "p46",
    title: "Science News Feed",
    description: "DOE, CERN, arXiv research feed",
    route: "/tools/science-news",
    category: "pages",
    icon: "BookOpen",
  },
  {
    id: "p47",
    title: "Cross-Section Plotter",
    description: "Live ENDF/B cross-section data",
    route: "/tools/cross-section-plotter",
    category: "pages",
    icon: "BookOpen",
  },
  {
    id: "p48",
    title: "Radiation Map",
    description: "Global background radiation levels",
    route: "/tools/radiation-map",
    category: "pages",
    icon: "BookOpen",
  },
  {
    id: "p49",
    title: "ML Emulator",
    description: "Neural network nuclear binding energy predictor",
    route: "/tools/ml-emulator",
    category: "pages",
    icon: "BookOpen",
  },
  {
    id: "p50",
    title: "Virtual Lab Tours",
    description: "360° tours of CERN, ITER, NIF",
    route: "/tools/lab-tours",
    category: "pages",
    icon: "BookOpen",
  },
  {
    id: "p51",
    title: "Nuclide Database",
    description: "Live IAEA + NNDC nuclide data",
    route: "/tools/nuclide-database",
    category: "pages",
    icon: "BookOpen",
  },
];

const elementData: SearchResult[] = [
  {
    id: "e1",
    title: "Hydrogen",
    description: "Atomic number 1, lightest element",
    route: "/visualizations/periodic-table?element=H",
    category: "elements",
    icon: "Atom",
    metadata: "H 1",
  },
  {
    id: "e2",
    title: "Helium",
    description: "Atomic number 2, noble gas",
    route: "/visualizations/periodic-table?element=He",
    category: "elements",
    icon: "Atom",
    metadata: "He 2",
  },
  {
    id: "e3",
    title: "Lithium",
    description: "Atomic number 3, alkali metal",
    route: "/visualizations/periodic-table?element=Li",
    category: "elements",
    icon: "Atom",
    metadata: "Li 3",
  },
  {
    id: "e4",
    title: "Beryllium",
    description: "Atomic number 4, alkaline earth metal",
    route: "/visualizations/periodic-table?element=Be",
    category: "elements",
    icon: "Atom",
    metadata: "Be 4",
  },
  {
    id: "e5",
    title: "Boron",
    description: "Atomic number 5, metalloid",
    route: "/visualizations/periodic-table?element=B",
    category: "elements",
    icon: "Atom",
    metadata: "B 5",
  },
  {
    id: "e6",
    title: "Carbon",
    description: "Atomic number 6, basis of organic chemistry",
    route: "/visualizations/periodic-table?element=C",
    category: "elements",
    icon: "Atom",
    metadata: "C 6",
  },
  {
    id: "e7",
    title: "Nitrogen",
    description: "Atomic number 7, diatomic gas",
    route: "/visualizations/periodic-table?element=N",
    category: "elements",
    icon: "Atom",
    metadata: "N 7",
  },
  {
    id: "e8",
    title: "Oxygen",
    description: "Atomic number 8, essential for life",
    route: "/visualizations/periodic-table?element=O",
    category: "elements",
    icon: "Atom",
    metadata: "O 8",
  },
  {
    id: "e9",
    title: "Fluorine",
    description: "Atomic number 9, most electronegative element",
    route: "/visualizations/periodic-table?element=F",
    category: "elements",
    icon: "Atom",
    metadata: "F 9",
  },
  {
    id: "e10",
    title: "Neon",
    description: "Atomic number 10, noble gas",
    route: "/visualizations/periodic-table?element=Ne",
    category: "elements",
    icon: "Atom",
    metadata: "Ne 10",
  },
  {
    id: "e11",
    title: "Sodium",
    description: "Atomic number 11, alkali metal",
    route: "/visualizations/periodic-table?element=Na",
    category: "elements",
    icon: "Atom",
    metadata: "Na 11",
  },
  {
    id: "e12",
    title: "Magnesium",
    description: "Atomic number 12, alkaline earth metal",
    route: "/visualizations/periodic-table?element=Mg",
    category: "elements",
    icon: "Atom",
    metadata: "Mg 12",
  },
  {
    id: "e13",
    title: "Aluminum",
    description: "Atomic number 13, lightweight metal",
    route: "/visualizations/periodic-table?element=Al",
    category: "elements",
    icon: "Atom",
    metadata: "Al 13",
  },
  {
    id: "e14",
    title: "Silicon",
    description: "Atomic number 14, semiconductor",
    route: "/visualizations/periodic-table?element=Si",
    category: "elements",
    icon: "Atom",
    metadata: "Si 14",
  },
  {
    id: "e15",
    title: "Phosphorus",
    description: "Atomic number 15, essential for DNA",
    route: "/visualizations/periodic-table?element=P",
    category: "elements",
    icon: "Atom",
    metadata: "P 15",
  },
  {
    id: "e16",
    title: "Sulfur",
    description: "Atomic number 16, yellow solid",
    route: "/visualizations/periodic-table?element=S",
    category: "elements",
    icon: "Atom",
    metadata: "S 16",
  },
  {
    id: "e17",
    title: "Chlorine",
    description: "Atomic number 17, halogen",
    route: "/visualizations/periodic-table?element=Cl",
    category: "elements",
    icon: "Atom",
    metadata: "Cl 17",
  },
  {
    id: "e18",
    title: "Argon",
    description: "Atomic number 18, noble gas",
    route: "/visualizations/periodic-table?element=Ar",
    category: "elements",
    icon: "Atom",
    metadata: "Ar 18",
  },
  {
    id: "e19",
    title: "Potassium",
    description: "Atomic number 19, alkali metal",
    route: "/visualizations/periodic-table?element=K",
    category: "elements",
    icon: "Atom",
    metadata: "K 19",
  },
  {
    id: "e20",
    title: "Calcium",
    description: "Atomic number 20, alkaline earth metal",
    route: "/visualizations/periodic-table?element=Ca",
    category: "elements",
    icon: "Atom",
    metadata: "Ca 20",
  },
  {
    id: "e21",
    title: "Iron",
    description: "Atomic number 26, transition metal",
    route: "/visualizations/periodic-table?element=Fe",
    category: "elements",
    icon: "Atom",
    metadata: "Fe 26",
  },
  {
    id: "e22",
    title: "Copper",
    description: "Atomic number 29, conductive metal",
    route: "/visualizations/periodic-table?element=Cu",
    category: "elements",
    icon: "Atom",
    metadata: "Cu 29",
  },
  {
    id: "e23",
    title: "Zinc",
    description: "Atomic number 30, transition metal",
    route: "/visualizations/periodic-table?element=Zn",
    category: "elements",
    icon: "Atom",
    metadata: "Zn 30",
  },
  {
    id: "e24",
    title: "Silver",
    description: "Atomic number 47, precious metal",
    route: "/visualizations/periodic-table?element=Ag",
    category: "elements",
    icon: "Atom",
    metadata: "Ag 47",
  },
  {
    id: "e25",
    title: "Gold",
    description: "Atomic number 79, precious metal",
    route: "/visualizations/periodic-table?element=Au",
    category: "elements",
    icon: "Atom",
    metadata: "Au 79",
  },
  {
    id: "e26",
    title: "Mercury",
    description: "Atomic number 80, liquid metal",
    route: "/visualizations/periodic-table?element=Hg",
    category: "elements",
    icon: "Atom",
    metadata: "Hg 80",
  },
  {
    id: "e27",
    title: "Lead",
    description: "Atomic number 82, heavy metal",
    route: "/visualizations/periodic-table?element=Pb",
    category: "elements",
    icon: "Atom",
    metadata: "Pb 82",
  },
  {
    id: "e28",
    title: "Uranium",
    description: "Atomic number 92, primary nuclear fuel",
    route: "/visualizations/periodic-table?element=U",
    category: "elements",
    icon: "Atom",
    metadata: "U 92",
  },
  {
    id: "e29",
    title: "Plutonium",
    description: "Atomic number 94, synthetic actinide",
    route: "/visualizations/periodic-table?element=Pu",
    category: "elements",
    icon: "Atom",
    metadata: "Pu 94",
  },
  {
    id: "e30",
    title: "Thorium",
    description: "Atomic number 90, fertile nuclear material",
    route: "/visualizations/periodic-table?element=Th",
    category: "elements",
    icon: "Atom",
    metadata: "Th 90",
  },
];

const toolData: SearchResult[] = [
  {
    id: "t1",
    title: "Data Explorer",
    description: "Sortable isotope data table",
    route: "/tools/data-explorer",
    category: "tools",
    icon: "Wrench",
  },
  {
    id: "t2",
    title: "Isotope Comparison",
    description: "Side-by-side isotope properties",
    route: "/tools/isotope-comparison",
    category: "tools",
    icon: "Wrench",
  },
  {
    id: "t3",
    title: "Radioisotope Database",
    description: "Searchable radioactive isotope database",
    route: "/tools/radioisotope-database",
    category: "tools",
    icon: "Wrench",
  },
  {
    id: "t4",
    title: "Cross-Section Viewer",
    description: "Neutron interaction cross-section plots",
    route: "/tools/cross-section-viewer",
    category: "tools",
    icon: "Wrench",
  },
  {
    id: "t5",
    title: "Dosimetry Calculator",
    description: "Calculate radiation dose and shielding",
    route: "/tools/dosimetry-calculator",
    category: "tools",
    icon: "Wrench",
  },
  {
    id: "t6",
    title: "Carbon Dating Calculator",
    description: "Radiocarbon age with IntCal20 calibration",
    route: "/tools/carbon-dating",
    category: "tools",
    icon: "Wrench",
  },
  {
    id: "t7",
    title: "Criticality Calculator",
    description: "k-effective and critical mass estimator",
    route: "/tools/criticality-calculator",
    category: "tools",
    icon: "Wrench",
  },
  {
    id: "t8",
    title: "Dose Rate Calculator",
    description: "Inverse-square law dose rate",
    route: "/tools/dose-rate-calculator",
    category: "tools",
    icon: "Wrench",
  },
  {
    id: "t9",
    title: "Fuel Cycle Visualizer",
    description: "Animated nuclear fuel cycle",
    route: "/tools/fuel-cycle",
    category: "tools",
    icon: "Wrench",
  },
  {
    id: "t10",
    title: "Monte Carlo Simulation",
    description: "Stochastic neutron transport",
    route: "/tools/monte-carlo-sim",
    category: "tools",
    icon: "Wrench",
  },
  {
    id: "t11",
    title: "Relativistic Kinematics",
    description: "Lorentz factor and Q-value calculator",
    route: "/tools/relativistic-kinematics",
    category: "tools",
    icon: "Wrench",
  },
  {
    id: "t12",
    title: "Science News Feed",
    description: "Latest nuclear research from DOE and CERN",
    route: "/tools/science-news",
    category: "tools",
    icon: "Wrench",
  },
  {
    id: "t13",
    title: "Cross-Section Plotter",
    description: "Live ENDF/B cross-section data",
    route: "/tools/cross-section-plotter",
    category: "tools",
    icon: "Wrench",
  },
  {
    id: "t14",
    title: "Radiation Map",
    description: "Global background radiation levels",
    route: "/tools/radiation-map",
    category: "tools",
    icon: "Wrench",
  },
  {
    id: "t15",
    title: "ML Emulator",
    description: "Neural network binding energy predictor",
    route: "/tools/ml-emulator",
    category: "tools",
    icon: "Wrench",
  },
  {
    id: "t16",
    title: "Virtual Lab Tours",
    description: "360° tours of CERN, ITER, NIF",
    route: "/tools/lab-tours",
    category: "tools",
    icon: "Wrench",
  },
  {
    id: "t17",
    title: "Nuclide Database",
    description: "Live IAEA + NNDC nuclide data",
    route: "/tools/nuclide-database",
    category: "tools",
    icon: "Wrench",
  },
  {
    id: "t18",
    title: "Shielding Calculator",
    description: "Material thickness and dose reduction",
    route: "/tools/shielding-calculator",
    category: "tools",
    icon: "Wrench",
  },
  {
    id: "t19",
    title: "Neutron Activation Calculator",
    description: "Activation products and half-lives",
    route: "/tools/neutron-activation",
    category: "tools",
    icon: "Wrench",
  },
  {
    id: "t20",
    title: "Isotope Production Simulator",
    description: "Cyclotron and reactor isotope production",
    route: "/tools/isotope-production",
    category: "tools",
    icon: "Wrench",
  },
];

const glossaryData: SearchResult[] = [
  {
    id: "g1",
    title: "Alpha Decay",
    description: "Emission of a helium-4 nucleus from a radioactive atom",
    route: "/glossary?term=alpha-decay",
    category: "glossary",
    icon: "BookMarked",
  },
  {
    id: "g2",
    title: "Beta Decay",
    description:
      "Transformation of a neutron into a proton with electron emission",
    route: "/glossary?term=beta-decay",
    category: "glossary",
    icon: "BookMarked",
  },
  {
    id: "g3",
    title: "Gamma Ray",
    description:
      "High-energy electromagnetic radiation from nuclear transitions",
    route: "/glossary?term=gamma-ray",
    category: "glossary",
    icon: "BookMarked",
  },
  {
    id: "g4",
    title: "Half-Life",
    description: "Time required for half of radioactive atoms to decay",
    route: "/glossary?term=half-life",
    category: "glossary",
    icon: "BookMarked",
  },
  {
    id: "g5",
    title: "Binding Energy",
    description: "Energy required to disassemble a nucleus into nucleons",
    route: "/glossary?term=binding-energy",
    category: "glossary",
    icon: "BookMarked",
  },
  {
    id: "g6",
    title: "Fission",
    description:
      "Nuclear reaction splitting a heavy nucleus into lighter fragments",
    route: "/glossary?term=fission",
    category: "glossary",
    icon: "BookMarked",
  },
  {
    id: "g7",
    title: "Fusion",
    description: "Nuclear reaction combining light nuclei into heavier ones",
    route: "/glossary?term=fusion",
    category: "glossary",
    icon: "BookMarked",
  },
  {
    id: "g8",
    title: "Neutron",
    description: "Neutral subatomic particle in the atomic nucleus",
    route: "/glossary?term=neutron",
    category: "glossary",
    icon: "BookMarked",
  },
  {
    id: "g9",
    title: "Proton",
    description: "Positively charged subatomic particle in the nucleus",
    route: "/glossary?term=proton",
    category: "glossary",
    icon: "BookMarked",
  },
  {
    id: "g10",
    title: "Electron",
    description: "Negatively charged subatomic particle orbiting the nucleus",
    route: "/glossary?term=electron",
    category: "glossary",
    icon: "BookMarked",
  },
  {
    id: "g11",
    title: "Isotope",
    description: "Atoms of the same element with different neutron numbers",
    route: "/glossary?term=isotope",
    category: "glossary",
    icon: "BookMarked",
  },
  {
    id: "g12",
    title: "Quark",
    description: "Fundamental particle composing protons and neutrons",
    route: "/glossary?term=quark",
    category: "glossary",
    icon: "BookMarked",
  },
  {
    id: "g13",
    title: "Control Rod",
    description: "Neutron-absorbing rod used to regulate reactor power",
    route: "/glossary?term=control-rod",
    category: "glossary",
    icon: "BookMarked",
  },
  {
    id: "g14",
    title: "Moderator",
    description: "Material that slows neutrons to thermal energies",
    route: "/glossary?term=moderator",
    category: "glossary",
    icon: "BookMarked",
  },
  {
    id: "g15",
    title: "Enrichment",
    description: "Process of increasing the proportion of U-235 in uranium",
    route: "/glossary?term=enrichment",
    category: "glossary",
    icon: "BookMarked",
  },
  {
    id: "g16",
    title: "Critical Mass",
    description: "Minimum fissile material needed to sustain a chain reaction",
    route: "/glossary?term=critical-mass",
    category: "glossary",
    icon: "BookMarked",
  },
  {
    id: "g17",
    title: "Cross-Section",
    description: "Effective target area for a nuclear reaction",
    route: "/glossary?term=cross-section",
    category: "glossary",
    icon: "BookMarked",
  },
  {
    id: "g18",
    title: "Sievert",
    description: "SI unit of equivalent radiation dose",
    route: "/glossary?term=sievert",
    category: "glossary",
    icon: "BookMarked",
  },
  {
    id: "g19",
    title: "Becquerel",
    description: "SI unit of radioactivity, one decay per second",
    route: "/glossary?term=becquerel",
    category: "glossary",
    icon: "BookMarked",
  },
  {
    id: "g20",
    title: "Curie",
    description: "Traditional unit of radioactivity, 3.7×10¹⁰ Bq",
    route: "/glossary?term=curie",
    category: "glossary",
    icon: "BookMarked",
  },
];

const allData = [...pageData, ...elementData, ...toolData, ...glossaryData];

const fuseOptions = {
  keys: ["title", "description", "metadata"],
  threshold: 0.35,
  includeMatches: true,
};

const fuse = new Fuse(allData, fuseOptions);

const RECENT_KEY = "nuclearedu-recent-searches";

function loadRecent(): string[] {
  try {
    const raw = localStorage.getItem(RECENT_KEY);
    if (raw) return JSON.parse(raw);
  } catch {
    // ignore
  }
  return [];
}

function saveRecent(searches: string[]) {
  try {
    localStorage.setItem(RECENT_KEY, JSON.stringify(searches.slice(0, 10)));
  } catch {
    // ignore
  }
}

export function useGlobalSearch() {
  const [query, setQuery] = useState("");
  const [selectedIndex, setSelectedIndex] = useState(0);
  const [isOpen, setIsOpen] = useState(false);
  const [recentSearches, setRecentSearches] = useState<string[]>(loadRecent);

  const results = useMemo(() => {
    if (!query.trim()) return [] as SearchResult[];
    const raw = fuse.search(query.trim(), { limit: 20 });
    return raw.map((r) => r.item);
  }, [query]);

  const addRecentSearch = useCallback((term: string) => {
    if (!term.trim()) return;
    setRecentSearches((prev) => {
      const next = [
        term.trim(),
        ...prev.filter((s) => s !== term.trim()),
      ].slice(0, 10);
      saveRecent(next);
      return next;
    });
  }, []);

  const clearRecentSearches = useCallback(() => {
    setRecentSearches([]);
    saveRecent([]);
  }, []);

  // biome-ignore lint/correctness/useExhaustiveDependencies: intentional reset on query change
  useEffect(() => {
    setSelectedIndex(0);
  }, [query]);

  return {
    query,
    setQuery,
    results,
    selectedIndex,
    setSelectedIndex,
    recentSearches,
    addRecentSearch,
    clearRecentSearches,
    isOpen,
    setIsOpen,
  };
}
