/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface IsotopePageResult {
  'records' : Array<IsotopeRecord>,
  'page' : bigint,
  'totalCount' : bigint,
  'pageSize' : bigint,
}
export interface IsotopeRecord {
  'n' : bigint,
  'z' : bigint,
  'branchingRatios' : Array<number>,
  'decayModes' : Array<string>,
  'name' : string,
  'lastUpdated' : string,
  'sourceUri' : string,
  'atomicMassAMU' : number,
  'massExcessKeV' : number,
  'bindingEnergyPerNucleon' : number,
  'abundance' : number,
  'halfLifeSeconds' : number,
  'qValueMeV' : number,
  'symbol' : string,
}
export type Result = { 'ok' : IsotopeRecord } |
  { 'err' : string };
export type Result_1 = { 'ok' : IsotopePageResult } |
  { 'err' : string };
export interface _SERVICE {
  'fetchAllIsotopesPage' : ActorMethod<[bigint, bigint], Result_1>,
  'fetchIsotopeData' : ActorMethod<[bigint, bigint], Result>,
  'getCachedIsotopeCount' : ActorMethod<[], bigint>,
  'getLastFetchTimestamp' : ActorMethod<[], bigint>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];