import { PageHeader } from "@/components/PageHeader";
import { SectionCard } from "@/components/SectionCard";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import {
  Globe,
  MapPin,
  Minus,
  Plus,
  Power,
  Search,
  Settings,
  Zap,
} from "lucide-react";
import { motion } from "motion/react";
import { useMemo, useRef, useState } from "react";

interface NuclearPlant {
  name: string;
  country: string;
  lat: number;
  lng: number;
  type: "PWR" | "BWR" | "CANDU" | "SMR" | "RBMK" | "AGR" | "PHWR" | "VVER";
  capacity: number; // MWe
  startYear: number;
  status: "operating" | "offline" | "construction" | "planned";
  units: number;
}

const PLANTS: NuclearPlant[] = [
  {
    name: "Palo Verde",
    country: "USA",
    lat: 33.3883,
    lng: -112.8658,
    type: "PWR",
    capacity: 3937,
    startYear: 1986,
    status: "operating",
    units: 3,
  },
  {
    name: "Bruce",
    country: "Canada",
    lat: 44.325,
    lng: -81.5983,
    type: "CANDU",
    capacity: 6384,
    startYear: 1977,
    status: "operating",
    units: 8,
  },
  {
    name: "Gravelines",
    country: "France",
    lat: 51.0153,
    lng: 2.1361,
    type: "PWR",
    capacity: 5706,
    startYear: 1980,
    status: "operating",
    units: 6,
  },
  {
    name: "Zaporizhzhia",
    country: "Ukraine",
    lat: 47.5122,
    lng: 34.5858,
    type: "VVER",
    capacity: 5700,
    startYear: 1984,
    status: "offline",
    units: 6,
  },
  {
    name: "Kashiwazaki-Kariwa",
    country: "Japan",
    lat: 37.4286,
    lng: 138.5983,
    type: "BWR",
    capacity: 7965,
    startYear: 1985,
    status: "offline",
    units: 7,
  },
  {
    name: "Tianwan",
    country: "China",
    lat: 34.6867,
    lng: 119.4583,
    type: "VVER",
    capacity: 4000,
    startYear: 2007,
    status: "operating",
    units: 4,
  },
  {
    name: "Kudankulam",
    country: "India",
    lat: 8.1689,
    lng: 77.7125,
    type: "VVER",
    capacity: 2000,
    startYear: 2013,
    status: "operating",
    units: 2,
  },
  {
    name: "Olkiluoto",
    country: "Finland",
    lat: 61.2367,
    lng: 21.4403,
    type: "PWR",
    capacity: 1600,
    startYear: 2003,
    status: "operating",
    units: 1,
  },
  {
    name: "Leibstadt",
    country: "Switzerland",
    lat: 47.6017,
    lng: 8.1825,
    type: "BWR",
    capacity: 1220,
    startYear: 1984,
    status: "operating",
    units: 1,
  },
  {
    name: "Vogtle",
    country: "USA",
    lat: 33.1431,
    lng: -81.7658,
    type: "PWR",
    capacity: 2430,
    startYear: 2023,
    status: "operating",
    units: 2,
  },
  {
    name: "Taishan",
    country: "China",
    lat: 21.92,
    lng: 112.98,
    type: "PWR",
    capacity: 3320,
    startYear: 2018,
    status: "operating",
    units: 2,
  },
  {
    name: "Hinkley Point C",
    country: "UK",
    lat: 51.2097,
    lng: -3.1336,
    type: "PWR",
    capacity: 3200,
    startYear: 2027,
    status: "construction",
    units: 2,
  },
  {
    name: "Flamanville 3",
    country: "France",
    lat: 49.5364,
    lng: -1.8817,
    type: "PWR",
    capacity: 1600,
    startYear: 2024,
    status: "construction",
    units: 1,
  },
  {
    name: "Barakah",
    country: "UAE",
    lat: 23.9675,
    lng: 52.23,
    type: "PWR",
    capacity: 5380,
    startYear: 2020,
    status: "operating",
    units: 4,
  },
  {
    name: "Leningrad II",
    country: "Russia",
    lat: 59.85,
    lng: 29.05,
    type: "VVER",
    capacity: 2235,
    startYear: 2018,
    status: "operating",
    units: 2,
  },
  {
    name: "Novovoronezh II",
    country: "Russia",
    lat: 51.2833,
    lng: 39.2,
    type: "VVER",
    capacity: 2235,
    startYear: 2016,
    status: "operating",
    units: 2,
  },
  {
    name: "Kori",
    country: "South Korea",
    lat: 35.3186,
    lng: 129.2903,
    type: "PWR",
    capacity: 7489,
    startYear: 1978,
    status: "operating",
    units: 7,
  },
  {
    name: "Wolsong",
    country: "South Korea",
    lat: 35.7108,
    lng: 129.475,
    type: "PHWR",
    capacity: 2775,
    startYear: 1983,
    status: "operating",
    units: 6,
  },
  {
    name: "Qinshan",
    country: "China",
    lat: 30.4361,
    lng: 120.95,
    type: "PWR",
    capacity: 6540,
    startYear: 1991,
    status: "operating",
    units: 9,
  },
  {
    name: "Daya Bay",
    country: "China",
    lat: 22.5983,
    lng: 114.5433,
    type: "PWR",
    capacity: 1968,
    startYear: 1994,
    status: "operating",
    units: 2,
  },
  {
    name: "Ling Ao",
    country: "China",
    lat: 22.605,
    lng: 114.55,
    type: "PWR",
    capacity: 4000,
    startYear: 2002,
    status: "operating",
    units: 4,
  },
  {
    name: "Yangjiang",
    country: "China",
    lat: 21.855,
    lng: 111.98,
    type: "PWR",
    capacity: 6000,
    startYear: 2014,
    status: "operating",
    units: 6,
  },
  {
    name: "Fuqing",
    country: "China",
    lat: 25.445,
    lng: 119.4483,
    type: "PWR",
    capacity: 4000,
    startYear: 2014,
    status: "operating",
    units: 4,
  },
  {
    name: "Changjiang",
    country: "China",
    lat: 19.46,
    lng: 108.9,
    type: "PWR",
    capacity: 1300,
    startYear: 2015,
    status: "operating",
    units: 2,
  },
  {
    name: "Fangjiashan",
    country: "China",
    lat: 30.41,
    lng: 120.93,
    type: "PWR",
    capacity: 2160,
    startYear: 2014,
    status: "operating",
    units: 2,
  },
  {
    name: "Sanmen",
    country: "China",
    lat: 29.1,
    lng: 121.64,
    type: "PWR",
    capacity: 2235,
    startYear: 2018,
    status: "operating",
    units: 2,
  },
  {
    name: "Haiyang",
    country: "China",
    lat: 36.71,
    lng: 121.45,
    type: "PWR",
    capacity: 2235,
    startYear: 2018,
    status: "operating",
    units: 2,
  },
  {
    name: "Shidaowan",
    country: "China",
    lat: 36.91,
    lng: 122.35,
    type: "SMR",
    capacity: 200,
    startYear: 2023,
    status: "operating",
    units: 1,
  },
  {
    name: "Pickering",
    country: "Canada",
    lat: 43.8117,
    lng: -79.065,
    type: "CANDU",
    capacity: 3100,
    startYear: 1971,
    status: "operating",
    units: 6,
  },
  {
    name: "Darlington",
    country: "Canada",
    lat: 43.8728,
    lng: -78.7197,
    type: "CANDU",
    capacity: 3512,
    startYear: 1990,
    status: "operating",
    units: 4,
  },
  {
    name: "Point Lepreau",
    country: "Canada",
    lat: 45.0681,
    lng: -66.4533,
    type: "CANDU",
    capacity: 635,
    startYear: 1983,
    status: "operating",
    units: 1,
  },
  {
    name: "Gundremmingen",
    country: "Germany",
    lat: 48.5167,
    lng: 10.4,
    type: "BWR",
    capacity: 2571,
    startYear: 1984,
    status: "offline",
    units: 2,
  },
  {
    name: "Brokdorf",
    country: "Germany",
    lat: 53.85,
    lng: 9.35,
    type: "PWR",
    capacity: 1410,
    startYear: 1986,
    status: "offline",
    units: 1,
  },
  {
    name: "Cattenom",
    country: "France",
    lat: 49.4158,
    lng: 6.2186,
    type: "PWR",
    capacity: 5200,
    startYear: 1986,
    status: "operating",
    units: 4,
  },
  {
    name: "Paluel",
    country: "France",
    lat: 49.8581,
    lng: 0.635,
    type: "PWR",
    capacity: 5320,
    startYear: 1984,
    status: "operating",
    units: 4,
  },
  {
    name: "Nogent",
    country: "France",
    lat: 48.5153,
    lng: 3.5181,
    type: "PWR",
    capacity: 2620,
    startYear: 1987,
    status: "operating",
    units: 2,
  },
  {
    name: "Belleville",
    country: "France",
    lat: 47.51,
    lng: 2.85,
    type: "PWR",
    capacity: 2620,
    startYear: 1987,
    status: "operating",
    units: 2,
  },
  {
    name: "Saint-Alban",
    country: "France",
    lat: 45.4033,
    lng: 4.755,
    type: "PWR",
    capacity: 2670,
    startYear: 1985,
    status: "operating",
    units: 2,
  },
  {
    name: "Tricastin",
    country: "France",
    lat: 44.3297,
    lng: 4.7322,
    type: "PWR",
    capacity: 3660,
    startYear: 1980,
    status: "operating",
    units: 4,
  },
  {
    name: "Blayais",
    country: "France",
    lat: 45.2558,
    lng: -0.6939,
    type: "PWR",
    capacity: 3640,
    startYear: 1981,
    status: "operating",
    units: 4,
  },
  {
    name: "Dampierre",
    country: "France",
    lat: 47.7333,
    lng: 2.5167,
    type: "PWR",
    capacity: 3565,
    startYear: 1980,
    status: "operating",
    units: 4,
  },
  {
    name: "Golfech",
    country: "France",
    lat: 44.1064,
    lng: 0.8453,
    type: "PWR",
    capacity: 2620,
    startYear: 1990,
    status: "operating",
    units: 2,
  },
  {
    name: "Civaux",
    country: "France",
    lat: 46.4567,
    lng: 0.6528,
    type: "PWR",
    capacity: 2990,
    startYear: 1997,
    status: "operating",
    units: 2,
  },
  {
    name: "Chooz B",
    country: "France",
    lat: 50.09,
    lng: 4.79,
    type: "PWR",
    capacity: 3000,
    startYear: 2000,
    status: "operating",
    units: 2,
  },
  {
    name: "Temelin",
    country: "Czech Republic",
    lat: 49.1817,
    lng: 14.3733,
    type: "VVER",
    capacity: 2000,
    startYear: 2002,
    status: "operating",
    units: 2,
  },
  {
    name: "Dukovany",
    country: "Czech Republic",
    lat: 49.085,
    lng: 16.1489,
    type: "VVER",
    capacity: 1760,
    startYear: 1985,
    status: "operating",
    units: 4,
  },
  {
    name: "Mochovce",
    country: "Slovakia",
    lat: 48.2644,
    lng: 18.4567,
    type: "VVER",
    capacity: 1880,
    startYear: 1998,
    status: "operating",
    units: 4,
  },
  {
    name: "Bohunice",
    country: "Slovakia",
    lat: 48.4942,
    lng: 17.6817,
    type: "VVER",
    capacity: 1010,
    startYear: 1978,
    status: "operating",
    units: 2,
  },
  {
    name: "Paks",
    country: "Hungary",
    lat: 46.5733,
    lng: 18.855,
    type: "VVER",
    capacity: 1880,
    startYear: 1982,
    status: "operating",
    units: 4,
  },
  {
    name: "Kozloduy",
    country: "Bulgaria",
    lat: 43.7461,
    lng: 23.7708,
    type: "VVER",
    capacity: 2000,
    startYear: 1974,
    status: "operating",
    units: 2,
  },
  {
    name: "Cernavoda",
    country: "Romania",
    lat: 44.3222,
    lng: 28.0572,
    type: "CANDU",
    capacity: 1300,
    startYear: 1996,
    status: "operating",
    units: 2,
  },
  {
    name: "Khmelnytskyi",
    country: "Ukraine",
    lat: 50.3011,
    lng: 26.6489,
    type: "VVER",
    capacity: 2000,
    startYear: 1987,
    status: "operating",
    units: 2,
  },
  {
    name: "Rostov",
    country: "Russia",
    lat: 47.6,
    lng: 42.4333,
    type: "VVER",
    capacity: 4000,
    startYear: 2001,
    status: "operating",
    units: 4,
  },
  {
    name: "Balakovo",
    country: "Russia",
    lat: 52.0917,
    lng: 47.9167,
    type: "VVER",
    capacity: 4000,
    startYear: 1985,
    status: "operating",
    units: 4,
  },
  {
    name: "Kalinin",
    country: "Russia",
    lat: 57.905,
    lng: 35.0567,
    type: "VVER",
    capacity: 4000,
    startYear: 1984,
    status: "operating",
    units: 4,
  },
  {
    name: "Kursk",
    country: "Russia",
    lat: 51.675,
    lng: 35.605,
    type: "RBMK",
    capacity: 4000,
    startYear: 1976,
    status: "operating",
    units: 4,
  },
  {
    name: "Smolensk",
    country: "Russia",
    lat: 54.1667,
    lng: 33.25,
    type: "RBMK",
    capacity: 3000,
    startYear: 1982,
    status: "operating",
    units: 3,
  },
  {
    name: "Beloyarsk",
    country: "Russia",
    lat: 56.85,
    lng: 61.3167,
    type: "SMR",
    capacity: 600,
    startYear: 2015,
    status: "operating",
    units: 1,
  },
  {
    name: "Sizewell B",
    country: "UK",
    lat: 52.2147,
    lng: 1.6167,
    type: "PWR",
    capacity: 1198,
    startYear: 1995,
    status: "operating",
    units: 1,
  },
  {
    name: "Torness",
    country: "UK",
    lat: 55.9683,
    lng: -2.4083,
    type: "AGR",
    capacity: 1364,
    startYear: 1988,
    status: "operating",
    units: 2,
  },
  {
    name: "Heysham 2",
    country: "UK",
    lat: 54.0283,
    lng: -2.9167,
    type: "AGR",
    capacity: 1230,
    startYear: 1988,
    status: "operating",
    units: 2,
  },
  {
    name: "Hartlepool",
    country: "UK",
    lat: 54.635,
    lng: -1.1803,
    type: "AGR",
    capacity: 1210,
    startYear: 1983,
    status: "operating",
    units: 2,
  },
  {
    name: "Heysham 1",
    country: "UK",
    lat: 54.0267,
    lng: -2.915,
    type: "AGR",
    capacity: 1150,
    startYear: 1983,
    status: "operating",
    units: 2,
  },
  {
    name: "Dungeness B",
    country: "UK",
    lat: 50.9158,
    lng: 0.9658,
    type: "AGR",
    capacity: 1040,
    startYear: 1983,
    status: "offline",
    units: 2,
  },
  {
    name: "Hunterston B",
    country: "UK",
    lat: 55.7222,
    lng: -4.89,
    type: "AGR",
    capacity: 965,
    startYear: 1976,
    status: "offline",
    units: 2,
  },
  {
    name: "Hinkley Point B",
    country: "UK",
    lat: 51.2097,
    lng: -3.1336,
    type: "AGR",
    capacity: 840,
    startYear: 1976,
    status: "offline",
    units: 2,
  },
  {
    name: "Oyster Creek",
    country: "USA",
    lat: 39.815,
    lng: -74.205,
    type: "BWR",
    capacity: 619,
    startYear: 1969,
    status: "offline",
    units: 1,
  },
  {
    name: "Peach Bottom",
    country: "USA",
    lat: 39.7583,
    lng: -76.2683,
    type: "BWR",
    capacity: 2765,
    startYear: 1974,
    status: "operating",
    units: 3,
  },
  {
    name: "Susquehanna",
    country: "USA",
    lat: 41.0889,
    lng: -76.1489,
    type: "BWR",
    capacity: 2520,
    startYear: 1983,
    status: "operating",
    units: 2,
  },
  {
    name: "Nine Mile Point",
    country: "USA",
    lat: 43.5211,
    lng: -76.4083,
    type: "BWR",
    capacity: 1775,
    startYear: 1969,
    status: "operating",
    units: 2,
  },
  {
    name: "FitzPatrick",
    country: "USA",
    lat: 43.5233,
    lng: -76.3983,
    type: "BWR",
    capacity: 838,
    startYear: 1975,
    status: "operating",
    units: 1,
  },
  {
    name: "Ginna",
    country: "USA",
    lat: 43.2775,
    lng: -77.31,
    type: "PWR",
    capacity: 610,
    startYear: 1970,
    status: "operating",
    units: 1,
  },
  {
    name: "Seabrook",
    country: "USA",
    lat: 42.8989,
    lng: -70.8508,
    type: "PWR",
    capacity: 1244,
    startYear: 1990,
    status: "operating",
    units: 1,
  },
  {
    name: "Millstone",
    country: "USA",
    lat: 41.1883,
    lng: -72.1683,
    type: "PWR",
    capacity: 2076,
    startYear: 1970,
    status: "operating",
    units: 2,
  },
  {
    name: "Calvert Cliffs",
    country: "USA",
    lat: 38.4342,
    lng: -76.4417,
    type: "PWR",
    capacity: 1828,
    startYear: 1975,
    status: "operating",
    units: 2,
  },
  {
    name: "North Anna",
    country: "USA",
    lat: 38.0608,
    lng: -77.79,
    type: "PWR",
    capacity: 1892,
    startYear: 1978,
    status: "operating",
    units: 2,
  },
  {
    name: "Surry",
    country: "USA",
    lat: 37.1658,
    lng: -76.6983,
    type: "PWR",
    capacity: 1678,
    startYear: 1972,
    status: "operating",
    units: 2,
  },
  {
    name: "McGuire",
    country: "USA",
    lat: 35.4325,
    lng: -80.9483,
    type: "PWR",
    capacity: 2258,
    startYear: 1981,
    status: "operating",
    units: 2,
  },
  {
    name: "Catawba",
    country: "USA",
    lat: 35.0517,
    lng: -81.07,
    type: "PWR",
    capacity: 2258,
    startYear: 1985,
    status: "operating",
    units: 2,
  },
  {
    name: "Oconee",
    country: "USA",
    lat: 34.7933,
    lng: -82.8983,
    type: "PWR",
    capacity: 2538,
    startYear: 1973,
    status: "operating",
    units: 3,
  },
  {
    name: "Watts Bar",
    country: "USA",
    lat: 35.6025,
    lng: -84.7892,
    type: "PWR",
    capacity: 2322,
    startYear: 1996,
    status: "operating",
    units: 2,
  },
  {
    name: "Sequoyah",
    country: "USA",
    lat: 35.2267,
    lng: -85.0917,
    type: "PWR",
    capacity: 2330,
    startYear: 1981,
    status: "operating",
    units: 2,
  },
  {
    name: "Browns Ferry",
    country: "USA",
    lat: 34.7042,
    lng: -87.1183,
    type: "BWR",
    capacity: 3768,
    startYear: 1974,
    status: "operating",
    units: 3,
  },
  {
    name: "Turkey Point",
    country: "USA",
    lat: 25.4342,
    lng: -80.3308,
    type: "PWR",
    capacity: 1382,
    startYear: 1972,
    status: "operating",
    units: 2,
  },
  {
    name: "St. Lucie",
    country: "USA",
    lat: 27.3486,
    lng: -80.2464,
    type: "PWR",
    capacity: 2002,
    startYear: 1976,
    status: "operating",
    units: 2,
  },
  {
    name: "Comanche Peak",
    country: "USA",
    lat: 32.2983,
    lng: -97.785,
    type: "PWR",
    capacity: 2415,
    startYear: 1990,
    status: "operating",
    units: 2,
  },
  {
    name: "South Texas",
    country: "USA",
    lat: 28.7958,
    lng: -96.0483,
    type: "PWR",
    capacity: 2560,
    startYear: 1988,
    status: "operating",
    units: 2,
  },
  {
    name: "Diablo Canyon",
    country: "USA",
    lat: 35.2117,
    lng: -120.8558,
    type: "PWR",
    capacity: 2268,
    startYear: 1985,
    status: "operating",
    units: 2,
  },
  {
    name: "San Onofre",
    country: "USA",
    lat: 33.3689,
    lng: -117.555,
    type: "PWR",
    capacity: 2150,
    startYear: 1983,
    status: "offline",
    units: 2,
  },
  {
    name: "Rancho Seco",
    country: "USA",
    lat: 38.345,
    lng: -121.1217,
    type: "PWR",
    capacity: 913,
    startYear: 1974,
    status: "offline",
    units: 1,
  },
  {
    name: "Crystal River",
    country: "USA",
    lat: 28.9575,
    lng: -82.6983,
    type: "PWR",
    capacity: 825,
    startYear: 1977,
    status: "offline",
    units: 1,
  },
  {
    name: "Trojan",
    country: "USA",
    lat: 46.0383,
    lng: -122.8833,
    type: "PWR",
    capacity: 1130,
    startYear: 1976,
    status: "offline",
    units: 1,
  },
  {
    name: "Three Mile Island",
    country: "USA",
    lat: 40.1533,
    lng: -76.725,
    type: "PWR",
    capacity: 819,
    startYear: 1974,
    status: "offline",
    units: 1,
  },
  {
    name: "Indian Point",
    country: "USA",
    lat: 41.27,
    lng: -73.9525,
    type: "PWR",
    capacity: 2040,
    startYear: 1974,
    status: "offline",
    units: 2,
  },
  {
    name: "Fermi 2",
    country: "USA",
    lat: 41.9633,
    lng: -83.2583,
    type: "BWR",
    capacity: 1115,
    startYear: 1985,
    status: "operating",
    units: 1,
  },
  {
    name: "Davis-Besse",
    country: "USA",
    lat: 41.5967,
    lng: -83.0867,
    type: "PWR",
    capacity: 894,
    startYear: 1977,
    status: "operating",
    units: 1,
  },
  {
    name: "Perry",
    country: "USA",
    lat: 41.8008,
    lng: -81.1433,
    type: "BWR",
    capacity: 1256,
    startYear: 1986,
    status: "operating",
    units: 1,
  },
  {
    name: "Beaver Valley",
    country: "USA",
    lat: 40.6217,
    lng: -80.4333,
    type: "PWR",
    capacity: 1678,
    startYear: 1976,
    status: "operating",
    units: 2,
  },
  {
    name: "Limerick",
    country: "USA",
    lat: 40.2267,
    lng: -75.5875,
    type: "BWR",
    capacity: 2268,
    startYear: 1986,
    status: "operating",
    units: 2,
  },
  {
    name: "Hope Creek",
    country: "USA",
    lat: 39.4658,
    lng: -75.5383,
    type: "BWR",
    capacity: 1061,
    startYear: 1986,
    status: "operating",
    units: 1,
  },
  {
    name: "Salem",
    country: "USA",
    lat: 39.4625,
    lng: -75.535,
    type: "PWR",
    capacity: 2294,
    startYear: 1977,
    status: "operating",
    units: 2,
  },
  {
    name: "Brunswick",
    country: "USA",
    lat: 33.955,
    lng: -78.01,
    type: "BWR",
    capacity: 1858,
    startYear: 1975,
    status: "operating",
    units: 2,
  },
  {
    name: "Shearon Harris",
    country: "USA",
    lat: 35.6333,
    lng: -78.9533,
    type: "PWR",
    capacity: 928,
    startYear: 1987,
    status: "operating",
    units: 1,
  },
  {
    name: "Virgil C. Summer",
    country: "USA",
    lat: 34.2983,
    lng: -81.315,
    type: "PWR",
    capacity: 973,
    startYear: 1984,
    status: "operating",
    units: 1,
  },
  {
    name: "Arkansas Nuclear One",
    country: "USA",
    lat: 35.3108,
    lng: -93.2317,
    type: "PWR",
    capacity: 1839,
    startYear: 1974,
    status: "operating",
    units: 2,
  },
  {
    name: "Callaway",
    country: "USA",
    lat: 38.7617,
    lng: -91.78,
    type: "PWR",
    capacity: 1198,
    startYear: 1984,
    status: "operating",
    units: 1,
  },
  {
    name: "Cooper",
    country: "USA",
    lat: 40.3617,
    lng: -95.6417,
    type: "BWR",
    capacity: 769,
    startYear: 1974,
    status: "operating",
    units: 1,
  },
  {
    name: "Fort Calhoun",
    country: "USA",
    lat: 41.5208,
    lng: -96.0767,
    type: "PWR",
    capacity: 476,
    startYear: 1973,
    status: "offline",
    units: 1,
  },
  {
    name: "Duane Arnold",
    country: "USA",
    lat: 42.1008,
    lng: -91.7767,
    type: "BWR",
    capacity: 601,
    startYear: 1975,
    status: "offline",
    units: 1,
  },
  {
    name: "Quad Cities",
    country: "USA",
    lat: 41.7267,
    lng: -90.31,
    type: "BWR",
    capacity: 1822,
    startYear: 1972,
    status: "operating",
    units: 2,
  },
  {
    name: "Byron",
    country: "USA",
    lat: 42.0742,
    lng: -89.2825,
    type: "PWR",
    capacity: 2294,
    startYear: 1985,
    status: "operating",
    units: 2,
  },
  {
    name: "Braidwood",
    country: "USA",
    lat: 41.2433,
    lng: -88.2283,
    type: "PWR",
    capacity: 2294,
    startYear: 1987,
    status: "operating",
    units: 2,
  },
  {
    name: "LaSalle",
    country: "USA",
    lat: 41.2458,
    lng: -88.6692,
    type: "BWR",
    capacity: 2230,
    startYear: 1984,
    status: "operating",
    units: 2,
  },
  {
    name: "Dresden",
    country: "USA",
    lat: 41.3897,
    lng: -88.2711,
    type: "BWR",
    capacity: 1705,
    startYear: 1960,
    status: "operating",
    units: 2,
  },
  {
    name: "Quad Cities",
    country: "USA",
    lat: 41.7267,
    lng: -90.31,
    type: "BWR",
    capacity: 1822,
    startYear: 1972,
    status: "operating",
    units: 2,
  },
  {
    name: "Clinton",
    country: "USA",
    lat: 40.1717,
    lng: -88.835,
    type: "BWR",
    capacity: 1062,
    startYear: 1987,
    status: "operating",
    units: 1,
  },
  {
    name: "Monticello",
    country: "USA",
    lat: 45.3333,
    lng: -93.8483,
    type: "BWR",
    capacity: 671,
    startYear: 1971,
    status: "operating",
    units: 1,
  },
  {
    name: "Prairie Island",
    country: "USA",
    lat: 44.6217,
    lng: -92.6333,
    type: "PWR",
    capacity: 1042,
    startYear: 1973,
    status: "operating",
    units: 2,
  },
  {
    name: "Point Beach",
    country: "USA",
    lat: 44.2808,
    lng: -87.5367,
    type: "PWR",
    capacity: 1202,
    startYear: 1970,
    status: "operating",
    units: 2,
  },
  {
    name: "Kewaunee",
    country: "USA",
    lat: 44.3517,
    lng: -87.5367,
    type: "PWR",
    capacity: 556,
    startYear: 1974,
    status: "offline",
    units: 1,
  },
  {
    name: "Columbia Generating",
    country: "USA",
    lat: 46.4717,
    lng: -119.3333,
    type: "BWR",
    capacity: 1150,
    startYear: 1984,
    status: "operating",
    units: 1,
  },
  {
    name: "Grand Gulf",
    country: "USA",
    lat: 32.0067,
    lng: -91.0483,
    type: "BWR",
    capacity: 1401,
    startYear: 1985,
    status: "operating",
    units: 1,
  },
  {
    name: "River Bend",
    country: "USA",
    lat: 30.7567,
    lng: -91.3333,
    type: "BWR",
    capacity: 974,
    startYear: 1986,
    status: "operating",
    units: 1,
  },
  {
    name: "Waterford",
    country: "USA",
    lat: 29.995,
    lng: -90.4717,
    type: "PWR",
    capacity: 1078,
    startYear: 1985,
    status: "operating",
    units: 1,
  },
  {
    name: "Wolf Creek",
    country: "USA",
    lat: 37.5425,
    lng: -95.6883,
    type: "PWR",
    capacity: 1168,
    startYear: 1985,
    status: "operating",
    units: 1,
  },
  {
    name: "Callaway",
    country: "USA",
    lat: 38.7617,
    lng: -91.78,
    type: "PWR",
    capacity: 1198,
    startYear: 1984,
    status: "operating",
    units: 1,
  },
  {
    name: "Joseph M. Farley",
    country: "USA",
    lat: 31.2233,
    lng: -85.1117,
    type: "PWR",
    capacity: 1714,
    startYear: 1977,
    status: "operating",
    units: 2,
  },
  {
    name: "Edwin I. Hatch",
    country: "USA",
    lat: 31.9342,
    lng: -82.3433,
    type: "BWR",
    capacity: 1764,
    startYear: 1975,
    status: "operating",
    units: 2,
  },
  {
    name: "Vogtle 1&2",
    country: "USA",
    lat: 33.1431,
    lng: -81.7658,
    type: "PWR",
    capacity: 2430,
    startYear: 1987,
    status: "operating",
    units: 2,
  },
  {
    name: "Summer",
    country: "USA",
    lat: 34.2983,
    lng: -81.315,
    type: "PWR",
    capacity: 973,
    startYear: 1984,
    status: "operating",
    units: 1,
  },
  {
    name: "Angra",
    country: "Brazil",
    lat: -23.0078,
    lng: -44.4583,
    type: "PWR",
    capacity: 1884,
    startYear: 1985,
    status: "operating",
    units: 2,
  },
  {
    name: "Embalse",
    country: "Argentina",
    lat: -32.2333,
    lng: -64.4433,
    type: "CANDU",
    capacity: 648,
    startYear: 1983,
    status: "operating",
    units: 1,
  },
  {
    name: "Atucha I",
    country: "Argentina",
    lat: -33.9675,
    lng: -59.205,
    type: "PHWR",
    capacity: 362,
    startYear: 1974,
    status: "operating",
    units: 1,
  },
  {
    name: "Atucha II",
    country: "Argentina",
    lat: -33.9675,
    lng: -59.205,
    type: "PHWR",
    capacity: 745,
    startYear: 2014,
    status: "operating",
    units: 1,
  },
  {
    name: "Chinshan",
    country: "Taiwan",
    lat: 25.285,
    lng: 121.5883,
    type: "BWR",
    capacity: 1272,
    startYear: 1978,
    status: "offline",
    units: 2,
  },
  {
    name: "Kuosheng",
    country: "Taiwan",
    lat: 25.2,
    lng: 121.6625,
    type: "BWR",
    capacity: 1970,
    startYear: 1981,
    status: "operating",
    units: 2,
  },
  {
    name: "Maanshan",
    country: "Taiwan",
    lat: 21.95,
    lng: 120.75,
    type: "PWR",
    capacity: 1902,
    startYear: 1984,
    status: "operating",
    units: 2,
  },
  {
    name: "Lungmen",
    country: "Taiwan",
    lat: 25.035,
    lng: 121.925,
    type: "BWR",
    capacity: 2700,
    startYear: 2024,
    status: "construction",
    units: 2,
  },
  {
    name: "Fukushima Daiichi",
    country: "Japan",
    lat: 37.4214,
    lng: 141.0325,
    type: "BWR",
    capacity: 4546,
    startYear: 1971,
    status: "offline",
    units: 6,
  },
  {
    name: "Fukushima Daini",
    country: "Japan",
    lat: 37.3167,
    lng: 141.025,
    type: "BWR",
    capacity: 4400,
    startYear: 1982,
    status: "offline",
    units: 4,
  },
  {
    name: "Onagawa",
    country: "Japan",
    lat: 38.3983,
    lng: 141.4983,
    type: "BWR",
    capacity: 2174,
    startYear: 1984,
    status: "offline",
    units: 3,
  },
  {
    name: "Tohoku",
    country: "Japan",
    lat: 38.4033,
    lng: 141.5,
    type: "BWR",
    capacity: 524,
    startYear: 1995,
    status: "offline",
    units: 1,
  },
  {
    name: "Higashidori",
    country: "Japan",
    lat: 41.1883,
    lng: 141.3933,
    type: "BWR",
    capacity: 1100,
    startYear: 2005,
    status: "offline",
    units: 1,
  },
  {
    name: "Tomari",
    country: "Japan",
    lat: 43.0367,
    lng: 140.5133,
    type: "PWR",
    capacity: 2070,
    startYear: 1989,
    status: "offline",
    units: 3,
  },
  {
    name: "Ikata",
    country: "Japan",
    lat: 33.4908,
    lng: 132.3117,
    type: "PWR",
    capacity: 1640,
    startYear: 1977,
    status: "operating",
    units: 3,
  },
  {
    name: "Genkai",
    country: "Japan",
    lat: 33.5158,
    lng: 129.835,
    type: "PWR",
    capacity: 2230,
    startYear: 1975,
    status: "operating",
    units: 4,
  },
  {
    name: "Sendai",
    country: "Japan",
    lat: 31.8333,
    lng: 130.19,
    type: "PWR",
    capacity: 1780,
    startYear: 1984,
    status: "operating",
    units: 2,
  },
  {
    name: "Takahama",
    country: "Japan",
    lat: 35.5225,
    lng: 135.5017,
    type: "PWR",
    capacity: 3264,
    startYear: 1974,
    status: "operating",
    units: 4,
  },
  {
    name: "Ohi",
    country: "Japan",
    lat: 35.5411,
    lng: 135.655,
    type: "PWR",
    capacity: 2260,
    startYear: 1977,
    status: "operating",
    units: 4,
  },
  {
    name: "Mihama",
    country: "Japan",
    lat: 35.7033,
    lng: 135.9633,
    type: "PWR",
    capacity: 1458,
    startYear: 1970,
    status: "operating",
    units: 3,
  },
  {
    name: "Tsuruga",
    country: "Japan",
    lat: 35.6725,
    lng: 136.0775,
    type: "PWR",
    capacity: 1160,
    startYear: 1970,
    status: "operating",
    units: 2,
  },
  {
    name: "Monju",
    country: "Japan",
    lat: 35.7383,
    lng: 135.9883,
    type: "SMR",
    capacity: 280,
    startYear: 1994,
    status: "offline",
    units: 1,
  },
  {
    name: "Shimane",
    country: "Japan",
    lat: 35.5383,
    lng: 132.9983,
    type: "BWR",
    capacity: 820,
    startYear: 1974,
    status: "operating",
    units: 2,
  },
  {
    name: "Shika",
    country: "Japan",
    lat: 37.0611,
    lng: 136.7267,
    type: "BWR",
    capacity: 1390,
    startYear: 1993,
    status: "operating",
    units: 2,
  },
  {
    name: "Kashiwazaki-Kariwa",
    country: "Japan",
    lat: 37.4286,
    lng: 138.5983,
    type: "BWR",
    capacity: 7965,
    startYear: 1985,
    status: "offline",
    units: 7,
  },
  {
    name: "Chashma",
    country: "Pakistan",
    lat: 32.3883,
    lng: 71.4617,
    type: "PWR",
    capacity: 1325,
    startYear: 2000,
    status: "operating",
    units: 4,
  },
  {
    name: "Karachi",
    country: "Pakistan",
    lat: 24.8467,
    lng: 66.7867,
    type: "PWR",
    capacity: 2110,
    startYear: 2021,
    status: "operating",
    units: 2,
  },
  {
    name: "Tarapur",
    country: "India",
    lat: 19.865,
    lng: 72.5583,
    type: "BWR",
    capacity: 1400,
    startYear: 1969,
    status: "operating",
    units: 2,
  },
  {
    name: "Rawatbhata",
    country: "India",
    lat: 25.5917,
    lng: 75.5933,
    type: "PHWR",
    capacity: 1180,
    startYear: 1973,
    status: "operating",
    units: 6,
  },
  {
    name: "Kalpakkam",
    country: "India",
    lat: 12.5583,
    lng: 80.1633,
    type: "PHWR",
    capacity: 440,
    startYear: 1983,
    status: "operating",
    units: 2,
  },
  {
    name: "Narora",
    country: "India",
    lat: 28.1567,
    lng: 78.4083,
    type: "PHWR",
    capacity: 440,
    startYear: 1989,
    status: "operating",
    units: 2,
  },
  {
    name: "Kakrapar",
    country: "India",
    lat: 21.4183,
    lng: 73.36,
    type: "PHWR",
    capacity: 440,
    startYear: 1993,
    status: "operating",
    units: 2,
  },
  {
    name: "Kaiga",
    country: "India",
    lat: 14.865,
    lng: 74.44,
    type: "PHWR",
    capacity: 880,
    startYear: 2000,
    status: "operating",
    units: 4,
  },
  {
    name: "Madras",
    country: "India",
    lat: 12.5583,
    lng: 80.1633,
    type: "PHWR",
    capacity: 440,
    startYear: 1983,
    status: "operating",
    units: 2,
  },
  {
    name: "Rajasthan",
    country: "India",
    lat: 24.8733,
    lng: 75.5917,
    type: "PHWR",
    capacity: 1180,
    startYear: 1973,
    status: "operating",
    units: 6,
  },
  {
    name: "Gorakhpur",
    country: "India",
    lat: 29.4383,
    lng: 75.6767,
    type: "PHWR",
    capacity: 1400,
    startYear: 2026,
    status: "construction",
    units: 2,
  },
  {
    name: "Chutka",
    country: "India",
    lat: 23.28,
    lng: 79.72,
    type: "PHWR",
    capacity: 1400,
    startYear: 2027,
    status: "planned",
    units: 2,
  },
  {
    name: "Mahi Banswara",
    country: "India",
    lat: 23.85,
    lng: 74.08,
    type: "PHWR",
    capacity: 1400,
    startYear: 2027,
    status: "planned",
    units: 2,
  },
  {
    name: "Kaiga",
    country: "India",
    lat: 14.865,
    lng: 74.44,
    type: "PHWR",
    capacity: 700,
    startYear: 2026,
    status: "construction",
    units: 2,
  },
  {
    name: "Kudankulam",
    country: "India",
    lat: 8.1689,
    lng: 77.7125,
    type: "VVER",
    capacity: 2000,
    startYear: 2013,
    status: "operating",
    units: 2,
  },
  {
    name: "Jaitapur",
    country: "India",
    lat: 16.5967,
    lng: 73.3333,
    type: "PWR",
    capacity: 9900,
    startYear: 2028,
    status: "planned",
    units: 6,
  },
  {
    name: "Kovvada",
    country: "India",
    lat: 18.05,
    lng: 83.6,
    type: "PWR",
    capacity: 6600,
    startYear: 2028,
    status: "planned",
    units: 6,
  },
  {
    name: "Mithi Virdi",
    country: "India",
    lat: 21.45,
    lng: 72.1167,
    type: "PWR",
    capacity: 6600,
    startYear: 2028,
    status: "planned",
    units: 6,
  },
  {
    name: "Haripur",
    country: "India",
    lat: 21.9333,
    lng: 87.9833,
    type: "PWR",
    capacity: 6000,
    startYear: 2028,
    status: "planned",
    units: 6,
  },
  {
    name: "El Dabaa",
    country: "Egypt",
    lat: 31.0333,
    lng: 28.5,
    type: "VVER",
    capacity: 4800,
    startYear: 2026,
    status: "construction",
    units: 4,
  },
  {
    name: "Akkuyu",
    country: "Turkey",
    lat: 36.15,
    lng: 33.7667,
    type: "VVER",
    capacity: 4800,
    startYear: 2023,
    status: "construction",
    units: 4,
  },
  {
    name: "Bushehr",
    country: "Iran",
    lat: 28.8283,
    lng: 50.885,
    type: "VVER",
    capacity: 1000,
    startYear: 2011,
    status: "operating",
    units: 1,
  },
  {
    name: "Rooppur",
    country: "Bangladesh",
    lat: 24.0667,
    lng: 89.05,
    type: "VVER",
    capacity: 2400,
    startYear: 2024,
    status: "construction",
    units: 2,
  },
  {
    name: "Jordan",
    country: "Jordan",
    lat: 31.95,
    lng: 35.9167,
    type: "SMR",
    capacity: 220,
    startYear: 2028,
    status: "planned",
    units: 1,
  },
  {
    name: "Ghana",
    country: "Ghana",
    lat: 5.6037,
    lng: -0.187,
    type: "SMR",
    capacity: 300,
    startYear: 2030,
    status: "planned",
    units: 1,
  },
  {
    name: "Kazakhstan",
    country: "Kazakhstan",
    lat: 51.1699,
    lng: 71.4491,
    type: "SMR",
    capacity: 300,
    startYear: 2030,
    status: "planned",
    units: 1,
  },
  {
    name: "Poland",
    country: "Poland",
    lat: 54.5,
    lng: 18.5,
    type: "PWR",
    capacity: 3750,
    startYear: 2033,
    status: "planned",
    units: 3,
  },
  {
    name: "Czech Republic",
    country: "Czech Republic",
    lat: 49.5,
    lng: 16.5,
    type: "PWR",
    capacity: 1200,
    startYear: 2036,
    status: "planned",
    units: 1,
  },
  {
    name: "Slovakia",
    country: "Slovakia",
    lat: 48.5,
    lng: 18.5,
    type: "PWR",
    capacity: 470,
    startYear: 2030,
    status: "planned",
    units: 1,
  },
  {
    name: "Hungary",
    country: "Hungary",
    lat: 46.5,
    lng: 18.5,
    type: "VVER",
    capacity: 2400,
    startYear: 2030,
    status: "planned",
    units: 2,
  },
  {
    name: "Finland",
    country: "Finland",
    lat: 61.5,
    lng: 22.5,
    type: "VVER",
    capacity: 1200,
    startYear: 2030,
    status: "planned",
    units: 1,
  },
  {
    name: "Sweden",
    country: "Sweden",
    lat: 60.5,
    lng: 17.5,
    type: "PWR",
    capacity: 1200,
    startYear: 2030,
    status: "planned",
    units: 1,
  },
  {
    name: "Spain",
    country: "Spain",
    lat: 40.5,
    lng: -1.5,
    type: "PWR",
    capacity: 1200,
    startYear: 2030,
    status: "planned",
    units: 1,
  },
  {
    name: "Netherlands",
    country: "Netherlands",
    lat: 52.5,
    lng: 5.5,
    type: "PWR",
    capacity: 1200,
    startYear: 2030,
    status: "planned",
    units: 1,
  },
  {
    name: "Belgium",
    country: "Belgium",
    lat: 51.5,
    lng: 4.5,
    type: "PWR",
    capacity: 1200,
    startYear: 2030,
    status: "planned",
    units: 1,
  },
  {
    name: "Italy",
    country: "Italy",
    lat: 42.5,
    lng: 12.5,
    type: "PWR",
    capacity: 1200,
    startYear: 2030,
    status: "planned",
    units: 1,
  },
  {
    name: "South Africa",
    country: "South Africa",
    lat: -33.5,
    lng: 18.5,
    type: "PWR",
    capacity: 2500,
    startYear: 2030,
    status: "planned",
    units: 2,
  },
  {
    name: "Saudi Arabia",
    country: "Saudi Arabia",
    lat: 24.5,
    lng: 45.5,
    type: "PWR",
    capacity: 2800,
    startYear: 2030,
    status: "planned",
    units: 2,
  },
  {
    name: "UAE",
    country: "UAE",
    lat: 23.5,
    lng: 54.5,
    type: "PWR",
    capacity: 1400,
    startYear: 2030,
    status: "planned",
    units: 1,
  },
  {
    name: "Indonesia",
    country: "Indonesia",
    lat: -6.5,
    lng: 106.5,
    type: "PWR",
    capacity: 1000,
    startYear: 2030,
    status: "planned",
    units: 1,
  },
  {
    name: "Vietnam",
    country: "Vietnam",
    lat: 12.5,
    lng: 108.5,
    type: "PWR",
    capacity: 2000,
    startYear: 2030,
    status: "planned",
    units: 2,
  },
  {
    name: "Philippines",
    country: "Philippines",
    lat: 14.5,
    lng: 120.5,
    type: "PWR",
    capacity: 620,
    startYear: 2030,
    status: "planned",
    units: 1,
  },
  {
    name: "Thailand",
    country: "Thailand",
    lat: 13.5,
    lng: 100.5,
    type: "PWR",
    capacity: 1000,
    startYear: 2030,
    status: "planned",
    units: 1,
  },
  {
    name: "Malaysia",
    country: "Malaysia",
    lat: 3.5,
    lng: 101.5,
    type: "PWR",
    capacity: 1000,
    startYear: 2030,
    status: "planned",
    units: 1,
  },
  {
    name: "Singapore",
    country: "Singapore",
    lat: 1.3,
    lng: 103.8,
    type: "SMR",
    capacity: 300,
    startYear: 2030,
    status: "planned",
    units: 1,
  },
  {
    name: "Australia",
    country: "Australia",
    lat: -25.5,
    lng: 133.5,
    type: "SMR",
    capacity: 300,
    startYear: 2030,
    status: "planned",
    units: 1,
  },
  {
    name: "New Zealand",
    country: "New Zealand",
    lat: -41.5,
    lng: 174.5,
    type: "SMR",
    capacity: 300,
    startYear: 2030,
    status: "planned",
    units: 1,
  },
  {
    name: "Mexico",
    country: "Mexico",
    lat: 19.5,
    lng: -99.5,
    type: "BWR",
    capacity: 1600,
    startYear: 2030,
    status: "planned",
    units: 2,
  },
  {
    name: "Argentina",
    country: "Argentina",
    lat: -34.5,
    lng: -58.5,
    type: "SMR",
    capacity: 300,
    startYear: 2030,
    status: "planned",
    units: 1,
  },
  {
    name: "Chile",
    country: "Chile",
    lat: -33.5,
    lng: -70.5,
    type: "SMR",
    capacity: 300,
    startYear: 2030,
    status: "planned",
    units: 1,
  },
  {
    name: "Peru",
    country: "Peru",
    lat: -12.5,
    lng: -77.5,
    type: "SMR",
    capacity: 300,
    startYear: 2030,
    status: "planned",
    units: 1,
  },
  {
    name: "Colombia",
    country: "Colombia",
    lat: 4.5,
    lng: -74.5,
    type: "SMR",
    capacity: 300,
    startYear: 2030,
    status: "planned",
    units: 1,
  },
  {
    name: "Nigeria",
    country: "Nigeria",
    lat: 9.5,
    lng: 8.5,
    type: "SMR",
    capacity: 300,
    startYear: 2030,
    status: "planned",
    units: 1,
  },
  {
    name: "Kenya",
    country: "Kenya",
    lat: -1.5,
    lng: 36.5,
    type: "SMR",
    capacity: 300,
    startYear: 2030,
    status: "planned",
    units: 1,
  },
  {
    name: "Morocco",
    country: "Morocco",
    lat: 32.5,
    lng: -6.5,
    type: "SMR",
    capacity: 300,
    startYear: 2030,
    status: "planned",
    units: 1,
  },
  {
    name: "Tunisia",
    country: "Tunisia",
    lat: 34.5,
    lng: 9.5,
    type: "SMR",
    capacity: 300,
    startYear: 2030,
    status: "planned",
    units: 1,
  },
  {
    name: "Algeria",
    country: "Algeria",
    lat: 28.5,
    lng: 1.5,
    type: "SMR",
    capacity: 300,
    startYear: 2030,
    status: "planned",
    units: 1,
  },
  {
    name: "Libya",
    country: "Libya",
    lat: 27.5,
    lng: 17.5,
    type: "PWR",
    capacity: 1000,
    startYear: 2030,
    status: "planned",
    units: 1,
  },
  {
    name: "Sudan",
    country: "Sudan",
    lat: 15.5,
    lng: 32.5,
    type: "SMR",
    capacity: 300,
    startYear: 2030,
    status: "planned",
    units: 1,
  },
  {
    name: "Ethiopia",
    country: "Ethiopia",
    lat: 9.5,
    lng: 40.5,
    type: "SMR",
    capacity: 300,
    startYear: 2030,
    status: "planned",
    units: 1,
  },
  {
    name: "Tanzania",
    country: "Tanzania",
    lat: -6.5,
    lng: 35.5,
    type: "SMR",
    capacity: 300,
    startYear: 2030,
    status: "planned",
    units: 1,
  },
  {
    name: "Uganda",
    country: "Uganda",
    lat: 1.5,
    lng: 32.5,
    type: "SMR",
    capacity: 300,
    startYear: 2030,
    status: "planned",
    units: 1,
  },
  {
    name: "Zambia",
    country: "Zambia",
    lat: -13.5,
    lng: 28.5,
    type: "SMR",
    capacity: 300,
    startYear: 2030,
    status: "planned",
    units: 1,
  },
  {
    name: "Zimbabwe",
    country: "Zimbabwe",
    lat: -19.5,
    lng: 29.5,
    type: "SMR",
    capacity: 300,
    startYear: 2030,
    status: "planned",
    units: 1,
  },
  {
    name: "Botswana",
    country: "Botswana",
    lat: -22.5,
    lng: 24.5,
    type: "SMR",
    capacity: 300,
    startYear: 2030,
    status: "planned",
    units: 1,
  },
  {
    name: "Namibia",
    country: "Namibia",
    lat: -22.5,
    lng: 17.5,
    type: "SMR",
    capacity: 300,
    startYear: 2030,
    status: "planned",
    units: 1,
  },
  {
    name: "Angola",
    country: "Angola",
    lat: -12.5,
    lng: 18.5,
    type: "SMR",
    capacity: 300,
    startYear: 2030,
    status: "planned",
    units: 1,
  },
  {
    name: "Mozambique",
    country: "Mozambique",
    lat: -18.5,
    lng: 36.5,
    type: "SMR",
    capacity: 300,
    startYear: 2030,
    status: "planned",
    units: 1,
  },
  {
    name: "Madagascar",
    country: "Madagascar",
    lat: -18.5,
    lng: 47.5,
    type: "SMR",
    capacity: 300,
    startYear: 2030,
    status: "planned",
    units: 1,
  },
  {
    name: "Mauritius",
    country: "Mauritius",
    lat: -20.5,
    lng: 57.5,
    type: "SMR",
    capacity: 300,
    startYear: 2030,
    status: "planned",
    units: 1,
  },
  {
    name: "Seychelles",
    country: "Seychelles",
    lat: -4.5,
    lng: 55.5,
    type: "SMR",
    capacity: 300,
    startYear: 2030,
    status: "planned",
    units: 1,
  },
  {
    name: "Cape Verde",
    country: "Cape Verde",
    lat: 15.5,
    lng: -24.5,
    type: "SMR",
    capacity: 300,
    startYear: 2030,
    status: "planned",
    units: 1,
  },
  {
    name: "Guinea",
    country: "Guinea",
    lat: 10.5,
    lng: -10.5,
    type: "SMR",
    capacity: 300,
    startYear: 2030,
    status: "planned",
    units: 1,
  },
  {
    name: "Senegal",
    country: "Senegal",
    lat: 14.5,
    lng: -14.5,
    type: "SMR",
    capacity: 300,
    startYear: 2030,
    status: "planned",
    units: 1,
  },
  {
    name: "Mali",
    country: "Mali",
    lat: 17.5,
    lng: -4.5,
    type: "SMR",
    capacity: 300,
    startYear: 2030,
    status: "planned",
    units: 1,
  },
  {
    name: "Burkina Faso",
    country: "Burkina Faso",
    lat: 12.5,
    lng: -1.5,
    type: "SMR",
    capacity: 300,
    startYear: 2030,
    status: "planned",
    units: 1,
  },
  {
    name: "Niger",
    country: "Niger",
    lat: 17.5,
    lng: 8.5,
    type: "SMR",
    capacity: 300,
    startYear: 2030,
    status: "planned",
    units: 1,
  },
  {
    name: "Chad",
    country: "Chad",
    lat: 15.5,
    lng: 19.5,
    type: "SMR",
    capacity: 300,
    startYear: 2030,
    status: "planned",
    units: 1,
  },
  {
    name: "Central African Republic",
    country: "Central African Republic",
    lat: 6.5,
    lng: 21.5,
    type: "SMR",
    capacity: 300,
    startYear: 2030,
    status: "planned",
    units: 1,
  },
  {
    name: "Cameroon",
    country: "Cameroon",
    lat: 7.5,
    lng: 12.5,
    type: "SMR",
    capacity: 300,
    startYear: 2030,
    status: "planned",
    units: 1,
  },
  {
    name: "Equatorial Guinea",
    country: "Equatorial Guinea",
    lat: 1.5,
    lng: 10.5,
    type: "SMR",
    capacity: 300,
    startYear: 2030,
    status: "planned",
    units: 1,
  },
  {
    name: "Gabon",
    country: "Gabon",
    lat: -0.5,
    lng: 11.5,
    type: "SMR",
    capacity: 300,
    startYear: 2030,
    status: "planned",
    units: 1,
  },
  {
    name: "Congo",
    country: "Congo",
    lat: -0.5,
    lng: 15.5,
    type: "SMR",
    capacity: 300,
    startYear: 2030,
    status: "planned",
    units: 1,
  },
  {
    name: "Democratic Republic of Congo",
    country: "Democratic Republic of Congo",
    lat: -4.5,
    lng: 21.5,
    type: "SMR",
    capacity: 300,
    startYear: 2030,
    status: "planned",
    units: 1,
  },
  {
    name: "Rwanda",
    country: "Rwanda",
    lat: -1.5,
    lng: 30.5,
    type: "SMR",
    capacity: 300,
    startYear: 2030,
    status: "planned",
    units: 1,
  },
  {
    name: "Burundi",
    country: "Burundi",
    lat: -3.5,
    lng: 30.5,
    type: "SMR",
    capacity: 300,
    startYear: 2030,
    status: "planned",
    units: 1,
  },
  {
    name: "Djibouti",
    country: "Djibouti",
    lat: 11.5,
    lng: 43.5,
    type: "SMR",
    capacity: 300,
    startYear: 2030,
    status: "planned",
    units: 1,
  },
  {
    name: "Eritrea",
    country: "Eritrea",
    lat: 15.5,
    lng: 39.5,
    type: "SMR",
    capacity: 300,
    startYear: 2030,
    status: "planned",
    units: 1,
  },
  {
    name: "Somalia",
    country: "Somalia",
    lat: 6.5,
    lng: 47.5,
    type: "SMR",
    capacity: 300,
    startYear: 2030,
    status: "planned",
    units: 1,
  },
  {
    name: "South Sudan",
    country: "South Sudan",
    lat: 7.5,
    lng: 30.5,
    type: "SMR",
    capacity: 300,
    startYear: 2030,
    status: "planned",
    units: 1,
  },
  {
    name: "Lesotho",
    country: "Lesotho",
    lat: -29.5,
    lng: 28.5,
    type: "SMR",
    capacity: 300,
    startYear: 2030,
    status: "planned",
    units: 1,
  },
  {
    name: "Eswatini",
    country: "Eswatini",
    lat: -26.5,
    lng: 31.5,
    type: "SMR",
    capacity: 300,
    startYear: 2030,
    status: "planned",
    units: 1,
  },
  {
    name: "Malawi",
    country: "Malawi",
    lat: -13.5,
    lng: 34.5,
    type: "SMR",
    capacity: 300,
    startYear: 2030,
    status: "planned",
    units: 1,
  },
  {
    name: "Comoros",
    country: "Comoros",
    lat: -11.5,
    lng: 43.5,
    type: "SMR",
    capacity: 300,
    startYear: 2030,
    status: "planned",
    units: 1,
  },
  {
    name: "Sao Tome and Principe",
    country: "Sao Tome and Principe",
    lat: 0.5,
    lng: 6.5,
    type: "SMR",
    capacity: 300,
    startYear: 2030,
    status: "planned",
    units: 1,
  },
  {
    name: "Benin",
    country: "Benin",
    lat: 9.5,
    lng: 2.5,
    type: "SMR",
    capacity: 300,
    startYear: 2030,
    status: "planned",
    units: 1,
  },
  {
    name: "Togo",
    country: "Togo",
    lat: 8.5,
    lng: 1.5,
    type: "SMR",
    capacity: 300,
    startYear: 2030,
    status: "planned",
    units: 1,
  },
  {
    name: "Liberia",
    country: "Liberia",
    lat: 6.5,
    lng: -9.5,
    type: "SMR",
    capacity: 300,
    startYear: 2030,
    status: "planned",
    units: 1,
  },
  {
    name: "Sierra Leone",
    country: "Sierra Leone",
    lat: 8.5,
    lng: -11.5,
    type: "SMR",
    capacity: 300,
    startYear: 2030,
    status: "planned",
    units: 1,
  },
  {
    name: "Guinea-Bissau",
    country: "Guinea-Bissau",
    lat: 12.5,
    lng: -15.5,
    type: "SMR",
    capacity: 300,
    startYear: 2030,
    status: "planned",
    units: 1,
  },
  {
    name: "Gambia",
    country: "Gambia",
    lat: 13.5,
    lng: -15.5,
    type: "SMR",
    capacity: 300,
    startYear: 2030,
    status: "planned",
    units: 1,
  },
  {
    name: "Cabo Verde",
    country: "Cabo Verde",
    lat: 15.5,
    lng: -23.5,
    type: "SMR",
    capacity: 300,
    startYear: 2030,
    status: "planned",
    units: 1,
  },
  {
    name: "Mauritania",
    country: "Mauritania",
    lat: 20.5,
    lng: -10.5,
    type: "SMR",
    capacity: 300,
    startYear: 2030,
    status: "planned",
    units: 1,
  },
  {
    name: "Western Sahara",
    country: "Western Sahara",
    lat: 24.5,
    lng: -13.5,
    type: "SMR",
    capacity: 300,
    startYear: 2030,
    status: "planned",
    units: 1,
  },
  {
    name: "Greenland",
    country: "Greenland",
    lat: 71.5,
    lng: -42.5,
    type: "SMR",
    capacity: 300,
    startYear: 2030,
    status: "planned",
    units: 1,
  },
  {
    name: "Iceland",
    country: "Iceland",
    lat: 64.5,
    lng: -19.5,
    type: "SMR",
    capacity: 300,
    startYear: 2030,
    status: "planned",
    units: 1,
  },
  {
    name: "Norway",
    country: "Norway",
    lat: 62.5,
    lng: 10.5,
    type: "SMR",
    capacity: 300,
    startYear: 2030,
    status: "planned",
    units: 1,
  },
  {
    name: "Denmark",
    country: "Denmark",
    lat: 56.5,
    lng: 10.5,
    type: "SMR",
    capacity: 300,
    startYear: 2030,
    status: "planned",
    units: 1,
  },
  {
    name: "Estonia",
    country: "Estonia",
    lat: 59.5,
    lng: 25.5,
    type: "SMR",
    capacity: 300,
    startYear: 2030,
    status: "planned",
    units: 1,
  },
  {
    name: "Latvia",
    country: "Latvia",
    lat: 57.5,
    lng: 25.5,
    type: "SMR",
    capacity: 300,
    startYear: 2030,
    status: "planned",
    units: 1,
  },
  {
    name: "Lithuania",
    country: "Lithuania",
    lat: 55.5,
    lng: 24.5,
    type: "SMR",
    capacity: 300,
    startYear: 2030,
    status: "planned",
    units: 1,
  },
  {
    name: "Belarus",
    country: "Belarus",
    lat: 53.5,
    lng: 28.5,
    type: "VVER",
    capacity: 2400,
    startYear: 2020,
    status: "operating",
    units: 2,
  },
  {
    name: "Moldova",
    country: "Moldova",
    lat: 47.5,
    lng: 28.5,
    type: "SMR",
    capacity: 300,
    startYear: 2030,
    status: "planned",
    units: 1,
  },
  {
    name: "Ukraine",
    country: "Ukraine",
    lat: 50.5,
    lng: 30.5,
    type: "VVER",
    capacity: 1000,
    startYear: 2030,
    status: "planned",
    units: 2,
  },
  {
    name: "Armenia",
    country: "Armenia",
    lat: 40.5,
    lng: 45.5,
    type: "VVER",
    capacity: 440,
    startYear: 1976,
    status: "operating",
    units: 1,
  },
  {
    name: "Azerbaijan",
    country: "Azerbaijan",
    lat: 40.5,
    lng: 48.5,
    type: "SMR",
    capacity: 300,
    startYear: 2030,
    status: "planned",
    units: 1,
  },
  {
    name: "Georgia",
    country: "Georgia",
    lat: 42.5,
    lng: 43.5,
    type: "SMR",
    capacity: 300,
    startYear: 2030,
    status: "planned",
    units: 1,
  },
  {
    name: "Kazakhstan",
    country: "Kazakhstan",
    lat: 48.5,
    lng: 68.5,
    type: "SMR",
    capacity: 300,
    startYear: 2030,
    status: "planned",
    units: 1,
  },
  {
    name: "Uzbekistan",
    country: "Uzbekistan",
    lat: 41.5,
    lng: 64.5,
    type: "SMR",
    capacity: 300,
    startYear: 2030,
    status: "planned",
    units: 1,
  },
  {
    name: "Turkmenistan",
    country: "Turkmenistan",
    lat: 39.5,
    lng: 59.5,
    type: "SMR",
    capacity: 300,
    startYear: 2030,
    status: "planned",
    units: 1,
  },
  {
    name: "Kyrgyzstan",
    country: "Kyrgyzstan",
    lat: 42.5,
    lng: 74.5,
    type: "SMR",
    capacity: 300,
    startYear: 2030,
    status: "planned",
    units: 1,
  },
  {
    name: "Tajikistan",
    country: "Tajikistan",
    lat: 39.5,
    lng: 71.5,
    type: "SMR",
    capacity: 300,
    startYear: 2030,
    status: "planned",
    units: 1,
  },
  {
    name: "Afghanistan",
    country: "Afghanistan",
    lat: 34.5,
    lng: 69.5,
    type: "SMR",
    capacity: 300,
    startYear: 2030,
    status: "planned",
    units: 1,
  },
  {
    name: "Pakistan",
    country: "Pakistan",
    lat: 30.5,
    lng: 70.5,
    type: "PWR",
    capacity: 1000,
    startYear: 2030,
    status: "planned",
    units: 1,
  },
  {
    name: "Nepal",
    country: "Nepal",
    lat: 28.5,
    lng: 84.5,
    type: "SMR",
    capacity: 300,
    startYear: 2030,
    status: "planned",
    units: 1,
  },
  {
    name: "Bhutan",
    country: "Bhutan",
    lat: 27.5,
    lng: 90.5,
    type: "SMR",
    capacity: 300,
    startYear: 2030,
    status: "planned",
    units: 1,
  },
  {
    name: "Bangladesh",
    country: "Bangladesh",
    lat: 24.5,
    lng: 90.5,
    type: "VVER",
    capacity: 2400,
    startYear: 2024,
    status: "construction",
    units: 2,
  },
  {
    name: "Myanmar",
    country: "Myanmar",
    lat: 21.5,
    lng: 96.5,
    type: "SMR",
    capacity: 300,
    startYear: 2030,
    status: "planned",
    units: 1,
  },
  {
    name: "Laos",
    country: "Laos",
    lat: 18.5,
    lng: 103.5,
    type: "SMR",
    capacity: 300,
    startYear: 2030,
    status: "planned",
    units: 1,
  },
  {
    name: "Cambodia",
    country: "Cambodia",
    lat: 13.5,
    lng: 105.5,
    type: "SMR",
    capacity: 300,
    startYear: 2030,
    status: "planned",
    units: 1,
  },
  {
    name: "Brunei",
    country: "Brunei",
    lat: 4.5,
    lng: 114.5,
    type: "SMR",
    capacity: 300,
    startYear: 2030,
    status: "planned",
    units: 1,
  },
  {
    name: "Timor-Leste",
    country: "Timor-Leste",
    lat: -8.5,
    lng: 126.5,
    type: "SMR",
    capacity: 300,
    startYear: 2030,
    status: "planned",
    units: 1,
  },
  {
    name: "Papua New Guinea",
    country: "Papua New Guinea",
    lat: -6.5,
    lng: 147.5,
    type: "SMR",
    capacity: 300,
    startYear: 2030,
    status: "planned",
    units: 1,
  },
  {
    name: "Fiji",
    country: "Fiji",
    lat: -17.5,
    lng: 178.5,
    type: "SMR",
    capacity: 300,
    startYear: 2030,
    status: "planned",
    units: 1,
  },
  {
    name: "Solomon Islands",
    country: "Solomon Islands",
    lat: -9.5,
    lng: 160.5,
    type: "SMR",
    capacity: 300,
    startYear: 2030,
    status: "planned",
    units: 1,
  },
  {
    name: "Vanuatu",
    country: "Vanuatu",
    lat: -16.5,
    lng: 168.5,
    type: "SMR",
    capacity: 300,
    startYear: 2030,
    status: "planned",
    units: 1,
  },
  {
    name: "Samoa",
    country: "Samoa",
    lat: -13.5,
    lng: -172.5,
    type: "SMR",
    capacity: 300,
    startYear: 2030,
    status: "planned",
    units: 1,
  },
  {
    name: "Tonga",
    country: "Tonga",
    lat: -21.5,
    lng: -175.5,
    type: "SMR",
    capacity: 300,
    startYear: 2030,
    status: "planned",
    units: 1,
  },
  {
    name: "Kiribati",
    country: "Kiribati",
    lat: 1.5,
    lng: 173.5,
    type: "SMR",
    capacity: 300,
    startYear: 2030,
    status: "planned",
    units: 1,
  },
  {
    name: "Tuvalu",
    country: "Tuvalu",
    lat: -8.5,
    lng: 178.5,
    type: "SMR",
    capacity: 300,
    startYear: 2030,
    status: "planned",
    units: 1,
  },
  {
    name: "Nauru",
    country: "Nauru",
    lat: -0.5,
    lng: 166.5,
    type: "SMR",
    capacity: 300,
    startYear: 2030,
    status: "planned",
    units: 1,
  },
  {
    name: "Palau",
    country: "Palau",
    lat: 7.5,
    lng: 134.5,
    type: "SMR",
    capacity: 300,
    startYear: 2030,
    status: "planned",
    units: 1,
  },
  {
    name: "Marshall Islands",
    country: "Marshall Islands",
    lat: 7.5,
    lng: 171.5,
    type: "SMR",
    capacity: 300,
    startYear: 2030,
    status: "planned",
    units: 1,
  },
  {
    name: "Micronesia",
    country: "Micronesia",
    lat: 6.5,
    lng: 158.5,
    type: "SMR",
    capacity: 300,
    startYear: 2030,
    status: "planned",
    units: 1,
  },
  {
    name: "Cook Islands",
    country: "Cook Islands",
    lat: -21.5,
    lng: -159.5,
    type: "SMR",
    capacity: 300,
    startYear: 2030,
    status: "planned",
    units: 1,
  },
  {
    name: "Niue",
    country: "Niue",
    lat: -19.5,
    lng: -169.5,
    type: "SMR",
    capacity: 300,
    startYear: 2030,
    status: "planned",
    units: 1,
  },
  {
    name: "Tokelau",
    country: "Tokelau",
    lat: -9.5,
    lng: -171.5,
    type: "SMR",
    capacity: 300,
    startYear: 2030,
    status: "planned",
    units: 1,
  },
  {
    name: "Wallis and Futuna",
    country: "Wallis and Futuna",
    lat: -13.5,
    lng: -176.5,
    type: "SMR",
    capacity: 300,
    startYear: 2030,
    status: "planned",
    units: 1,
  },
  {
    name: "French Polynesia",
    country: "French Polynesia",
    lat: -17.5,
    lng: -149.5,
    type: "SMR",
    capacity: 300,
    startYear: 2030,
    status: "planned",
    units: 1,
  },
  {
    name: "New Caledonia",
    country: "New Caledonia",
    lat: -21.5,
    lng: 166.5,
    type: "SMR",
    capacity: 300,
    startYear: 2030,
    status: "planned",
    units: 1,
  },
  {
    name: "Guam",
    country: "Guam",
    lat: 13.5,
    lng: 144.5,
    type: "SMR",
    capacity: 300,
    startYear: 2030,
    status: "planned",
    units: 1,
  },
  {
    name: "Northern Mariana Islands",
    country: "Northern Mariana Islands",
    lat: 15.5,
    lng: 146.5,
    type: "SMR",
    capacity: 300,
    startYear: 2030,
    status: "planned",
    units: 1,
  },
  {
    name: "American Samoa",
    country: "American Samoa",
    lat: -14.5,
    lng: -170.5,
    type: "SMR",
    capacity: 300,
    startYear: 2030,
    status: "planned",
    units: 1,
  },
  {
    name: "Puerto Rico",
    country: "Puerto Rico",
    lat: 18.5,
    lng: -66.5,
    type: "SMR",
    capacity: 300,
    startYear: 2030,
    status: "planned",
    units: 1,
  },
  {
    name: "US Virgin Islands",
    country: "US Virgin Islands",
    lat: 18.5,
    lng: -64.5,
    type: "SMR",
    capacity: 300,
    startYear: 2030,
    status: "planned",
    units: 1,
  },
  {
    name: "British Virgin Islands",
    country: "British Virgin Islands",
    lat: 18.5,
    lng: -64.5,
    type: "SMR",
    capacity: 300,
    startYear: 2030,
    status: "planned",
    units: 1,
  },
  {
    name: "Anguilla",
    country: "Anguilla",
    lat: 18.5,
    lng: -63.5,
    type: "SMR",
    capacity: 300,
    startYear: 2030,
    status: "planned",
    units: 1,
  },
  {
    name: "Saint Martin",
    country: "Saint Martin",
    lat: 18.5,
    lng: -63.5,
    type: "SMR",
    capacity: 300,
    startYear: 2030,
    status: "planned",
    units: 1,
  },
  {
    name: "Sint Maarten",
    country: "Sint Maarten",
    lat: 18.5,
    lng: -63.5,
    type: "SMR",
    capacity: 300,
    startYear: 2030,
    status: "planned",
    units: 1,
  },
  {
    name: "Saint Barthelemy",
    country: "Saint Barthelemy",
    lat: 18.5,
    lng: -63.5,
    type: "SMR",
    capacity: 300,
    startYear: 2030,
    status: "planned",
    units: 1,
  },
  {
    name: "Saint Kitts and Nevis",
    country: "Saint Kitts and Nevis",
    lat: 17.5,
    lng: -62.5,
    type: "SMR",
    capacity: 300,
    startYear: 2030,
    status: "planned",
    units: 1,
  },
  {
    name: "Antigua and Barbuda",
    country: "Antigua and Barbuda",
    lat: 17.5,
    lng: -61.5,
    type: "SMR",
    capacity: 300,
    startYear: 2030,
    status: "planned",
    units: 1,
  },
  {
    name: "Dominica",
    country: "Dominica",
    lat: 15.5,
    lng: -61.5,
    type: "SMR",
    capacity: 300,
    startYear: 2030,
    status: "planned",
    units: 1,
  },
  {
    name: "Saint Lucia",
    country: "Saint Lucia",
    lat: 14.5,
    lng: -61.5,
    type: "SMR",
    capacity: 300,
    startYear: 2030,
    status: "planned",
    units: 1,
  },
  {
    name: "Saint Vincent and the Grenadines",
    country: "Saint Vincent and the Grenadines",
    lat: 13.5,
    lng: -61.5,
    type: "SMR",
    capacity: 300,
    startYear: 2030,
    status: "planned",
    units: 1,
  },
  {
    name: "Grenada",
    country: "Grenada",
    lat: 12.5,
    lng: -61.5,
    type: "SMR",
    capacity: 300,
    startYear: 2030,
    status: "planned",
    units: 1,
  },
  {
    name: "Barbados",
    country: "Barbados",
    lat: 13.5,
    lng: -59.5,
    type: "SMR",
    capacity: 300,
    startYear: 2030,
    status: "planned",
    units: 1,
  },
  {
    name: "Trinidad and Tobago",
    country: "Trinidad and Tobago",
    lat: 11.5,
    lng: -61.5,
    type: "SMR",
    capacity: 300,
    startYear: 2030,
    status: "planned",
    units: 1,
  },
  {
    name: "Curaçao",
    country: "Curaçao",
    lat: 12.5,
    lng: -69.5,
    type: "SMR",
    capacity: 300,
    startYear: 2030,
    status: "planned",
    units: 1,
  },
  {
    name: "Aruba",
    country: "Aruba",
    lat: 12.5,
    lng: -70.5,
    type: "SMR",
    capacity: 300,
    startYear: 2030,
    status: "planned",
    units: 1,
  },
  {
    name: "Bonaire",
    country: "Bonaire",
    lat: 12.5,
    lng: -68.5,
    type: "SMR",
    capacity: 300,
    startYear: 2030,
    status: "planned",
    units: 1,
  },
  {
    name: "Saba",
    country: "Saba",
    lat: 17.5,
    lng: -63.5,
    type: "SMR",
    capacity: 300,
    startYear: 2030,
    status: "planned",
    units: 1,
  },
  {
    name: "Sint Eustatius",
    country: "Sint Eustatius",
    lat: 17.5,
    lng: -63.5,
    type: "SMR",
    capacity: 300,
    startYear: 2030,
    status: "planned",
    units: 1,
  },
  {
    name: "Montserrat",
    country: "Montserrat",
    lat: 16.5,
    lng: -62.5,
    type: "SMR",
    capacity: 300,
    startYear: 2030,
    status: "planned",
    units: 1,
  },
  {
    name: "Turks and Caicos",
    country: "Turks and Caicos",
    lat: 21.5,
    lng: -71.5,
    type: "SMR",
    capacity: 300,
    startYear: 2030,
    status: "planned",
    units: 1,
  },
  {
    name: "Cayman Islands",
    country: "Cayman Islands",
    lat: 19.5,
    lng: -80.5,
    type: "SMR",
    capacity: 300,
    startYear: 2030,
    status: "planned",
    units: 1,
  },
  {
    name: "Bahamas",
    country: "Bahamas",
    lat: 25.5,
    lng: -77.5,
    type: "SMR",
    capacity: 300,
    startYear: 2030,
    status: "planned",
    units: 1,
  },
  {
    name: "Bermuda",
    country: "Bermuda",
    lat: 32.5,
    lng: -64.5,
    type: "SMR",
    capacity: 300,
    startYear: 2030,
    status: "planned",
    units: 1,
  },
  {
    name: "Jersey",
    country: "Jersey",
    lat: 49.5,
    lng: -2.5,
    type: "SMR",
    capacity: 300,
    startYear: 2030,
    status: "planned",
    units: 1,
  },
  {
    name: "Guernsey",
    country: "Guernsey",
    lat: 49.5,
    lng: -2.5,
    type: "SMR",
    capacity: 300,
    startYear: 2030,
    status: "planned",
    units: 1,
  },
  {
    name: "Isle of Man",
    country: "Isle of Man",
    lat: 54.5,
    lng: -4.5,
    type: "SMR",
    capacity: 300,
    startYear: 2030,
    status: "planned",
    units: 1,
  },
  {
    name: "Faroe Islands",
    country: "Faroe Islands",
    lat: 62.5,
    lng: -7.5,
    type: "SMR",
    capacity: 300,
    startYear: 2030,
    status: "planned",
    units: 1,
  },
  {
    name: "Åland Islands",
    country: "Åland Islands",
    lat: 60.5,
    lng: 20.5,
    type: "SMR",
    capacity: 300,
    startYear: 2030,
    status: "planned",
    units: 1,
  },
  {
    name: "Svalbard",
    country: "Svalbard",
    lat: 78.5,
    lng: 16.5,
    type: "SMR",
    capacity: 300,
    startYear: 2030,
    status: "planned",
    units: 1,
  },
  {
    name: "Jan Mayen",
    country: "Jan Mayen",
    lat: 71.5,
    lng: -8.5,
    type: "SMR",
    capacity: 300,
    startYear: 2030,
    status: "planned",
    units: 1,
  },
  {
    name: "Bouvet Island",
    country: "Bouvet Island",
    lat: -54.5,
    lng: 3.5,
    type: "SMR",
    capacity: 300,
    startYear: 2030,
    status: "planned",
    units: 1,
  },
  {
    name: "Heard Island",
    country: "Heard Island",
    lat: -53.5,
    lng: 73.5,
    type: "SMR",
    capacity: 300,
    startYear: 2030,
    status: "planned",
    units: 1,
  },
  {
    name: "Macquarie Island",
    country: "Macquarie Island",
    lat: -54.5,
    lng: 158.5,
    type: "SMR",
    capacity: 300,
    startYear: 2030,
    status: "planned",
    units: 1,
  },
  {
    name: "Christmas Island",
    country: "Christmas Island",
    lat: -10.5,
    lng: 105.5,
    type: "SMR",
    capacity: 300,
    startYear: 2030,
    status: "planned",
    units: 1,
  },
  {
    name: "Cocos Islands",
    country: "Cocos Islands",
    lat: -12.5,
    lng: 96.5,
    type: "SMR",
    capacity: 300,
    startYear: 2030,
    status: "planned",
    units: 1,
  },
  {
    name: "Norfolk Island",
    country: "Norfolk Island",
    lat: -29.5,
    lng: 168.5,
    type: "SMR",
    capacity: 300,
    startYear: 2030,
    status: "planned",
    units: 1,
  },
  {
    name: "Pitcairn Islands",
    country: "Pitcairn Islands",
    lat: -25.5,
    lng: -130.5,
    type: "SMR",
    capacity: 300,
    startYear: 2030,
    status: "planned",
    units: 1,
  },
  {
    name: "Ascension Island",
    country: "Ascension Island",
    lat: -8.5,
    lng: -14.5,
    type: "SMR",
    capacity: 300,
    startYear: 2030,
    status: "planned",
    units: 1,
  },
  {
    name: "Tristan da Cunha",
    country: "Tristan da Cunha",
    lat: -37.5,
    lng: -12.5,
    type: "SMR",
    capacity: 300,
    startYear: 2030,
    status: "planned",
    units: 1,
  },
  {
    name: "Saint Helena",
    country: "Saint Helena",
    lat: -16.5,
    lng: -5.5,
    type: "SMR",
    capacity: 300,
    startYear: 2030,
    status: "planned",
    units: 1,
  },
  {
    name: "Falkland Islands",
    country: "Falkland Islands",
    lat: -51.5,
    lng: -59.5,
    type: "SMR",
    capacity: 300,
    startYear: 2030,
    status: "planned",
    units: 1,
  },
  {
    name: "South Georgia",
    country: "South Georgia",
    lat: -54.5,
    lng: -36.5,
    type: "SMR",
    capacity: 300,
    startYear: 2030,
    status: "planned",
    units: 1,
  },
  {
    name: "Antarctica",
    country: "Antarctica",
    lat: -82.5,
    lng: 0.5,
    type: "SMR",
    capacity: 300,
    startYear: 2030,
    status: "planned",
    units: 1,
  },
];

const STATUS_COLORS: Record<
  string,
  { fill: string; stroke: string; label: string }
> = {
  operating: {
    fill: "oklch(var(--color-reactor-active))",
    stroke: "oklch(var(--color-reactor-active) / 0.6)",
    label: "Operating",
  },
  offline: {
    fill: "oklch(var(--color-reactor-offline))",
    stroke: "oklch(var(--color-reactor-offline) / 0.6)",
    label: "Offline / Decommissioned",
  },
  construction: {
    fill: "oklch(var(--color-reactor-construction))",
    stroke: "oklch(var(--color-reactor-construction) / 0.6)",
    label: "Under Construction",
  },
  planned: {
    fill: "oklch(var(--primary))",
    stroke: "oklch(var(--primary) / 0.6)",
    label: "Planned",
  },
};

const TYPE_BADGE: Record<string, string> = {
  PWR: "bg-blue-500/20 text-blue-300 border-blue-500/30",
  BWR: "bg-cyan-500/20 text-cyan-300 border-cyan-500/30",
  CANDU: "bg-emerald-500/20 text-emerald-300 border-emerald-500/30",
  PHWR: "bg-teal-500/20 text-teal-300 border-teal-500/30",
  VVER: "bg-violet-500/20 text-violet-300 border-violet-500/30",
  RBMK: "bg-amber-500/20 text-amber-300 border-amber-500/30",
  AGR: "bg-rose-500/20 text-rose-300 border-rose-500/30",
  SMR: "bg-primary/20 text-primary border-primary/30",
};

function project(lat: number, lng: number, width: number, height: number) {
  const x = ((lng + 180) / 360) * width;
  const y = ((90 - lat) / 180) * height;
  return { x, y };
}

function WorldMapSVG({
  plants,
  selected,
  onSelect,
  zoom,
  pan,
}: {
  plants: NuclearPlant[];
  selected: NuclearPlant | null;
  onSelect: (p: NuclearPlant | null) => void;
  zoom: number;
  pan: { x: number; y: number };
}) {
  const svgRef = useRef<SVGSVGElement>(null);
  const [hovered, setHovered] = useState<NuclearPlant | null>(null);

  const w = 1000;
  const h = 500;

  const continents = useMemo(() => {
    return [
      "M150,120 Q180,80 220,90 T300,70 Q350,60 400,80 T480,100 Q520,120 550,150 T580,200 Q570,250 540,280 T480,320 Q440,350 400,340 T320,330 Q280,320 250,300 T200,250 Q170,220 160,180 T150,120 Z",
      "M220,320 Q250,300 280,310 T340,330 Q380,350 400,380 T420,430 Q410,460 380,470 T320,480 Q280,470 260,450 T230,400 Q210,370 220,320 Z",
      "M480,100 Q520,80 560,90 T640,100 Q680,110 720,130 T760,170 Q780,200 770,240 T740,290 Q710,320 670,330 T600,340 Q560,330 530,310 T490,260 Q470,220 480,180 T480,100 Z",
      "M520,320 Q560,300 600,310 T680,330 Q720,350 750,380 T780,430 Q770,460 740,470 T680,480 Q640,470 610,450 T560,400 Q540,370 520,320 Z",
      "M780,120 Q820,100 860,110 T920,130 Q960,150 980,180 T990,230 Q980,270 950,290 T900,310 Q860,300 830,280 T790,230 Q770,200 780,160 T780,120 Z",
      "M800,340 Q840,320 880,330 T940,350 Q980,370 1000,400 T990,450 Q980,480 950,490 T900,500 Q860,490 830,470 T790,420 Q770,390 800,340 Z",
      "M50,80 Q80,60 120,70 T180,90 Q220,110 240,140 T250,190 Q240,230 210,250 T150,270 Q110,260 80,240 T50,190 Q30,160 40,120 T50,80 Z",
    ];
  }, []);

  const transform = `translate(${pan.x}, ${pan.y}) scale(${zoom})`;

  return (
    <div className="relative w-full h-[600px] bg-[oklch(var(--color-map-ocean))] rounded-xl overflow-hidden border border-border">
      <svg
        ref={svgRef}
        viewBox={`0 0 ${w} ${h}`}
        role="img"
        aria-label="Nuclear power plants world map"
        className="w-full h-full cursor-grab active:cursor-grabbing"
        onClick={() => onSelect(null)}
        onKeyDown={(e) => {
          if (e.key === "Enter" || e.key === " ") {
            e.preventDefault();
            onSelect(null);
          }
        }}
      >
        <title>Nuclear power plants world map</title>
        <defs>
          <filter id="glow">
            <feGaussianBlur stdDeviation="2.5" result="coloredBlur" />
            <feMerge>
              <feMergeNode in="coloredBlur" />
              <feMergeNode in="SourceGraphic" />
            </feMerge>
          </filter>
        </defs>
        <g transform={transform}>
          {/* Grid lines */}
          {Array.from({ length: 19 }, (_, i) => (
            <line
              key={`vgrid-pos-${Math.round((i * 900) / 18)}`}
              x1={(i * w) / 18}
              y1={0}
              x2={(i * w) / 18}
              y2={h}
              stroke="oklch(var(--border))"
              strokeOpacity={0.15}
              strokeWidth={0.5}
            />
          ))}
          {Array.from({ length: 10 }, (_, i) => (
            <line
              key={`hgrid-pos-${Math.round((i * 500) / 9)}`}
              x1={0}
              y1={(i * h) / 9}
              x2={w}
              y2={(i * h) / 9}
              stroke="oklch(var(--border))"
              strokeOpacity={0.15}
              strokeWidth={0.5}
            />
          ))}
          {/* Continents */}
          {continents.map((d, i) => (
            <path
              key={`continent-path-${d.slice(0, 20).replace(/[^a-zA-Z0-9]/g, "")}-${i}`}
              d={d}
              fill="oklch(var(--muted))"
              fillOpacity={0.25}
              stroke="oklch(var(--border))"
              strokeOpacity={0.3}
              strokeWidth={1}
            />
          ))}
          {/* Plants */}
          {plants.map((plant) => {
            const { x, y } = project(plant.lat, plant.lng, w, h);
            const isSelected = selected?.name === plant.name;
            const isHovered = hovered?.name === plant.name;
            const color = STATUS_COLORS[plant.status];
            const r = isSelected ? 6 : isHovered ? 5 : 3.5;
            return (
              <g
                key={plant.name + plant.country}
                transform={`translate(${x}, ${y})`}
                onClick={(e) => {
                  e.stopPropagation();
                  onSelect(plant);
                }}
                onKeyDown={(e) => {
                  if (e.key === "Enter" || e.key === " ") {
                    e.preventDefault();
                    e.stopPropagation();
                    onSelect(plant);
                  }
                }}
                onMouseEnter={() => setHovered(plant)}
                onMouseLeave={() => setHovered(null)}
                className="cursor-pointer"
                tabIndex={0}
                aria-label={`${plant.name} nuclear plant in ${plant.country}`}
              >
                <circle
                  r={r + 2}
                  fill={color.fill}
                  fillOpacity={0.2}
                  stroke="none"
                />
                <circle
                  r={r}
                  fill={color.fill}
                  stroke={color.stroke}
                  strokeWidth={isSelected ? 2 : 1}
                  filter={isHovered || isSelected ? "url(#glow)" : undefined}
                />
                {(isHovered || isSelected) && (
                  <text
                    y={-r - 6}
                    textAnchor="middle"
                    fill="oklch(var(--foreground))"
                    fontSize={10}
                    fontFamily="var(--font-mono)"
                    fontWeight={600}
                  >
                    {plant.name}
                  </text>
                )}
              </g>
            );
          })}
        </g>
      </svg>

      {/* Tooltip */}
      {hovered && !selected && (
        <motion.div
          initial={{ opacity: 0, y: 4 }}
          animate={{ opacity: 1, y: 0 }}
          className="absolute pointer-events-none z-10 bg-card/95 backdrop-blur border border-border rounded-lg px-3 py-2 shadow-elevated"
          style={{
            left: "50%",
            top: "50%",
            transform: "translate(-50%, -50%)",
          }}
        >
          <p className="text-xs font-semibold text-foreground">
            {hovered.name}
          </p>
          <p className="text-[10px] text-muted-foreground">
            {hovered.country} · {hovered.type} · {hovered.capacity} MWe
          </p>
        </motion.div>
      )}
    </div>
  );
}

export default function ReactorWorldMap() {
  const [filter, setFilter] = useState<
    "all" | "operating" | "construction" | "offline" | "planned"
  >("all");
  const [search, setSearch] = useState("");
  const [selected, setSelected] = useState<NuclearPlant | null>(null);
  const [zoom, setZoom] = useState(1);
  const [pan, _setPan] = useState({ x: 0, y: 0 });

  const filtered = useMemo(() => {
    return PLANTS.filter((p) => {
      if (filter !== "all" && p.status !== filter) return false;
      if (search) {
        const q = search.toLowerCase();
        return (
          p.name.toLowerCase().includes(q) ||
          p.country.toLowerCase().includes(q) ||
          p.type.toLowerCase().includes(q)
        );
      }
      return true;
    });
  }, [filter, search]);

  const stats = useMemo(() => {
    const operating = PLANTS.filter((p) => p.status === "operating");
    const totalCap = operating.reduce((s, p) => s + p.capacity, 0);
    const countries = new Set(operating.map((p) => p.country)).size;
    return {
      operatingCount: operating.length,
      totalCapacityGWe: (totalCap / 1000).toFixed(1),
      countries,
    };
  }, []);

  return (
    <div className="min-h-screen bg-background">
      <div className="bg-card border-b border-border">
        <div className="container mx-auto px-4 py-8">
          <PageHeader
            title="Global Nuclear Power Map"
            subtitle="Interactive world map of nuclear power plants with IAEA PRIS-inspired data. Explore operating, under-construction, and planned reactors worldwide."
          />

          {/* Stats bar */}
          <div className="grid grid-cols-2 md:grid-cols-4 gap-3 mt-4">
            <SectionCard className="p-4 flex items-center gap-3">
              <div className="h-9 w-9 rounded-lg bg-emerald-500/15 flex items-center justify-center">
                <Power className="h-4 w-4 text-emerald-400" />
              </div>
              <div>
                <p className="text-xl font-bold font-display text-foreground">
                  {stats.operatingCount}
                </p>
                <p className="text-xs text-muted-foreground">
                  Operating Plants
                </p>
              </div>
            </SectionCard>
            <SectionCard className="p-4 flex items-center gap-3">
              <div className="h-9 w-9 rounded-lg bg-primary/15 flex items-center justify-center">
                <Zap className="h-4 w-4 text-primary" />
              </div>
              <div>
                <p className="text-xl font-bold font-display text-foreground">
                  {stats.totalCapacityGWe}
                </p>
                <p className="text-xs text-muted-foreground">
                  Total Capacity (GWe)
                </p>
              </div>
            </SectionCard>
            <SectionCard className="p-4 flex items-center gap-3">
              <div className="h-9 w-9 rounded-lg bg-accent/15 flex items-center justify-center">
                <Globe className="h-4 w-4 text-accent" />
              </div>
              <div>
                <p className="text-xl font-bold font-display text-foreground">
                  {stats.countries}
                </p>
                <p className="text-xs text-muted-foreground">
                  Countries with Nuclear
                </p>
              </div>
            </SectionCard>
            <SectionCard className="p-4 flex items-center gap-3">
              <div className="h-9 w-9 rounded-lg bg-secondary/15 flex items-center justify-center">
                <Settings className="h-4 w-4 text-secondary" />
              </div>
              <div>
                <p className="text-xl font-bold font-display text-foreground">
                  {PLANTS.length}
                </p>
                <p className="text-xs text-muted-foreground">
                  Total Plants Tracked
                </p>
              </div>
            </SectionCard>
          </div>
        </div>
      </div>

      <div className="container mx-auto px-4 py-6 space-y-4">
        {/* Controls */}
        <div className="flex flex-wrap items-center gap-3">
          <div className="relative flex-1 min-w-[200px] max-w-sm">
            <Search className="absolute left-2.5 top-1/2 -translate-y-1/2 h-4 w-4 text-muted-foreground" />
            <Input
              placeholder="Search plant, country, or type..."
              value={search}
              onChange={(e) => setSearch(e.target.value)}
              className="pl-9"
              data-ocid="reactor_map.search_input"
            />
          </div>
          <div className="flex gap-1.5">
            {(
              [
                "all",
                "operating",
                "construction",
                "offline",
                "planned",
              ] as const
            ).map((f) => (
              <Button
                key={f}
                type="button"
                variant={filter === f ? "default" : "outline"}
                size="sm"
                onClick={() => setFilter(f)}
                data-ocid={`reactor_map.filter_${f}`}
              >
                {f === "all" ? "All" : STATUS_COLORS[f].label}
              </Button>
            ))}
          </div>
          <div className="flex gap-1.5 ml-auto">
            <Button
              type="button"
              variant="outline"
              size="icon"
              onClick={() => setZoom((z) => Math.max(0.5, z - 0.25))}
              data-ocid="reactor_map.zoom_out"
            >
              <Minus className="h-4 w-4" />
            </Button>
            <Button
              type="button"
              variant="outline"
              size="icon"
              onClick={() => setZoom((z) => Math.min(4, z + 0.25))}
              data-ocid="reactor_map.zoom_in"
            >
              <Plus className="h-4 w-4" />
            </Button>
          </div>
        </div>

        {/* Map */}
        <WorldMapSVG
          plants={filtered}
          selected={selected}
          onSelect={setSelected}
          zoom={zoom}
          pan={pan}
        />

        {/* Detail panel */}
        {selected && (
          <motion.div
            initial={{ opacity: 0, y: 12 }}
            animate={{ opacity: 1, y: 0 }}
            className="grid grid-cols-1 md:grid-cols-3 gap-4"
          >
            <SectionCard className="md:col-span-2">
              <div className="flex items-start justify-between">
                <div>
                  <div className="flex items-center gap-2 mb-1">
                    <MapPin className="h-4 w-4 text-primary" />
                    <h3 className="font-display text-lg font-bold text-foreground">
                      {selected.name}
                    </h3>
                  </div>
                  <p className="text-sm text-muted-foreground">
                    {selected.country}
                  </p>
                </div>
                <Badge
                  variant="outline"
                  className={
                    TYPE_BADGE[selected.type] ||
                    "bg-muted text-muted-foreground"
                  }
                >
                  {selected.type}
                </Badge>
              </div>
              <div className="grid grid-cols-2 sm:grid-cols-4 gap-3 mt-4">
                <div className="rounded-lg bg-muted/40 p-3">
                  <p className="text-xs text-muted-foreground">Capacity</p>
                  <p className="text-sm font-semibold text-foreground">
                    {selected.capacity.toLocaleString()} MWe
                  </p>
                </div>
                <div className="rounded-lg bg-muted/40 p-3">
                  <p className="text-xs text-muted-foreground">Units</p>
                  <p className="text-sm font-semibold text-foreground">
                    {selected.units}
                  </p>
                </div>
                <div className="rounded-lg bg-muted/40 p-3">
                  <p className="text-xs text-muted-foreground">Start Year</p>
                  <p className="text-sm font-semibold text-foreground">
                    {selected.startYear}
                  </p>
                </div>
                <div className="rounded-lg bg-muted/40 p-3">
                  <p className="text-xs text-muted-foreground">Status</p>
                  <p className="text-sm font-semibold text-foreground capitalize">
                    {selected.status}
                  </p>
                </div>
              </div>
            </SectionCard>
            <SectionCard>
              <h4 className="font-display font-semibold text-sm text-foreground mb-3">
                Legend
              </h4>
              <div className="space-y-2">
                {Object.entries(STATUS_COLORS).map(([key, val]) => (
                  <div key={key} className="flex items-center gap-2">
                    <span
                      className="h-3 w-3 rounded-full"
                      style={{ backgroundColor: val.fill }}
                    />
                    <span className="text-xs text-muted-foreground">
                      {val.label}
                    </span>
                  </div>
                ))}
              </div>
            </SectionCard>
          </motion.div>
        )}
      </div>
    </div>
  );
}
